"""Notes / conversation / canonical-intent router. Thin adapter
(docs/adr/0001, 0020, 0021, FR-16). Capture is unmetered; STT/LLM/TTS
processing is metered in the service. Providers are injected via the
seam (fakes in tests)."""

from __future__ import annotations

import datetime
import uuid
from typing import Annotated, Any

from fastapi import APIRouter, Depends, Header, HTTPException, Query, status
from pydantic import BaseModel, Field
from sqlalchemy import select

from flow_api.deps import TenantCtx, tenant_ctx
from flow_api.routers.attachments import att_out, read_capped, upload_file_field
from flow_api.schemas import (
    AppendMessageIn,
    AppendOut,
    AttachmentOut,
    CommandIn,
    ConversationStartIn,
    DerivedTaskOut,
    EditSessionSealIn,
    EditSessionSealOut,
    ExpectedVersionIn,
    NoteCreateIn,
    NoteDeriveTaskIn,
    NoteEraseOut,
    NoteLinkIn,
    NoteLinkOut,
    NoteAppendIn,
    NoteOut,
    NotePatchIn,
    NotePromoteIn,
    NoteSetMaturityIn,
    NoteTagIn,
    NoteTaskLinkIn,
    NoteTaskLinkOut,
    NoteTranscribeIn,
    NoteTurnOut,
    NoteWithLinksOut,
    RevisionOut,
    RevisionRestoreIn,
    RevisionSummaryIn,
    SynthesizeIn,
    SynthOut,
    TagBrief,
    VersionOut,
)
from flow_core.db import admin_session
from flow_core.models.note import Note, NoteKind, NoteTurn
from flow_core.models.project_profile import ProjectProfile
from flow_core.models.tag import Tag, TagKind
from flow_core.services import agent_tokens as agent_tokens_svc
from flow_core.services import attachments as att_svc
from flow_core.services import entity_revisions as rev_svc
from flow_core.services import note_links as note_links_svc
from flow_core.services import notes as svc

router = APIRouter(prefix="/notes", tags=["notes"])


def _brief(tag: Tag) -> TagBrief:
    return TagBrief(id=tag.id, kind=tag.kind, name=tag.name, color=tag.color)


def _out(
    n: Note,
    tags: list[Tag] | None = None,
    primary_task_id: uuid.UUID | None = None,
    derived_task_ids: list[uuid.UUID] | None = None,
    linked_task_count: int = 0,
) -> NoteOut:
    # docs/adr/0029 P3: ``task_id`` exposed in the API is derived
    # from the typed link table (primary_task_id_for_note). Callers
    # batch-load the map for list endpoints; the single-note path
    # may pass the value explicitly. ``derived_task_ids`` is the full
    # list of tasks generated by the note (derived_from + promoted_from),
    # used by the SPA's "N tasks" chip on the note row.
    # ``linked_task_count`` (task 1e07437e) is the total of typed
    # links across every kind (subject, artifact, derived_from,
    # promoted_from); the chip now reflects this so subject/artifact-
    # only links also surface.
    return NoteOut(
        id=n.id,
        project_id=n.project_id,
        task_id=primary_task_id,
        kind=n.kind,
        status=n.status,
        title=n.title,
        transcript=n.transcript,
        summary=n.summary,
        audio_ref=n.audio_ref,
        is_archived=n.is_archived,
        deleted_at=n.deleted_at,
        tags=[_brief(t) for t in (tags or [])],
        version=n.version,
        maturity=n.maturity,
        promoted_at=n.promoted_at,
        derived_task_ids=list(derived_task_ids or []),
        linked_task_count=linked_task_count,
    )


def _link_out(link: Any) -> NoteLinkOut:
    return NoteLinkOut(
        id=link.id,
        parent_note_id=link.parent_note_id,
        child_note_id=link.child_note_id,
        kind=link.kind,
        created_by=link.created_by,
        created_at=link.created_at,
    )


def _task_link_out(link: Any) -> NoteTaskLinkOut:
    return NoteTaskLinkOut(
        id=link.id,
        note_id=link.note_id,
        task_id=link.task_id,
        kind=link.kind,
        created_by=link.created_by,
        created_at=link.created_at,
    )


def _turn(t: NoteTurn) -> NoteTurnOut:
    return NoteTurnOut(id=t.id, role=t.role, content=t.content, ord=t.ord)


@router.post("", response_model=NoteOut)
async def create_note(
    body: NoteCreateIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx)],
) -> NoteOut:
    n = await svc.create_note(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        kind=body.kind,
        project_id=body.project_id,
        title=body.title,
        text=body.text,
        audio_ref=body.audio_ref,
        audio_seconds=body.audio_seconds,
    )
    # Return the note with its tags: create() enforces a client
    # (default "Personal"), so the response must reflect it.
    tagmap = await svc.tags_by_note(ctx.session, note_ids=[n.id])
    pid = await note_links_svc.primary_task_id_for_note(
        ctx.session, org_id=ctx.org_id, note_id=n.id
    )
    derived = await note_links_svc.derived_task_ids_for_notes(
        ctx.session, org_id=ctx.org_id, note_ids=[n.id]
    )
    return _out(
        n,
        tagmap.get(n.id, []),
        primary_task_id=pid,
        derived_task_ids=derived.get(n.id, []),
    )


@router.get(
    "/links",
    response_model=list[NoteLinkOut],
    tags=["garden"],
)
async def list_workspace_note_links(
    ctx: Annotated[TenantCtx, Depends(tenant_ctx)],
) -> list[NoteLinkOut]:
    # Garden mindmap (ADR-0029 P2): single round-trip for the full
    # edge set in the workspace. Declared before ``GET /{note_id}``
    # because that catch-all would otherwise capture "links" as a
    # ``note_id`` path parameter and fail UUID validation with 422.
    rows = await note_links_svc.list_workspace_note_links(ctx.session, org_id=ctx.org_id)
    return [_link_out(r) for r in rows]


@router.get("", response_model=list[NoteOut])
async def list_notes(
    ctx: Annotated[TenantCtx, Depends(tenant_ctx)],
    include_archived: bool = False,
    include_deleted: bool = False,
    project_id: uuid.UUID | None = None,
    tag_id: uuid.UUID | None = None,
) -> list[NoteOut]:
    rows = await svc.list_notes(
        ctx.session,
        org_id=ctx.org_id,
        include_archived=include_archived,
        include_deleted=include_deleted,
        project_id=project_id,
        tag_id=tag_id,
    )
    ids = [n.id for n in rows]
    tagmap = await svc.tags_by_note(ctx.session, note_ids=ids)
    pid_map = await note_links_svc.primary_task_ids_for_notes(
        ctx.session, org_id=ctx.org_id, note_ids=ids
    )
    derived_map = await note_links_svc.derived_task_ids_for_notes(
        ctx.session, org_id=ctx.org_id, note_ids=ids
    )
    count_map = await note_links_svc.linked_task_counts_for_notes(
        ctx.session, org_id=ctx.org_id, note_ids=ids
    )
    return [
        _out(
            n,
            tagmap.get(n.id, []),
            primary_task_id=pid_map.get(n.id),
            derived_task_ids=derived_map.get(n.id, []),
            linked_task_count=count_map.get(n.id, 0),
        )
        for n in rows
    ]


@router.get("/{note_id}", response_model=NoteOut)
async def get_note(
    note_id: uuid.UUID,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx)],
) -> NoteOut:
    n = await svc.get_note(ctx.session, org_id=ctx.org_id, note_id=note_id)
    tagmap = await svc.tags_by_note(ctx.session, note_ids=[n.id])
    pid = await note_links_svc.primary_task_id_for_note(
        ctx.session, org_id=ctx.org_id, note_id=n.id
    )
    derived = await note_links_svc.derived_task_ids_for_notes(
        ctx.session, org_id=ctx.org_id, note_ids=[n.id]
    )
    counts = await note_links_svc.linked_task_counts_for_notes(
        ctx.session, org_id=ctx.org_id, note_ids=[n.id]
    )
    return _out(
        n,
        tagmap.get(n.id, []),
        primary_task_id=pid,
        derived_task_ids=derived.get(n.id, []),
        linked_task_count=counts.get(n.id, 0),
    )


@router.post("/{note_id}/tags", status_code=204)
async def attach_note_tag(
    note_id: uuid.UUID,
    body: NoteTagIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx)],
) -> None:
    await svc.attach_tag(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        tag_id=body.tag_id,
    )


@router.delete("/{note_id}/tags/{tag_id}", status_code=204)
async def detach_note_tag(
    note_id: uuid.UUID,
    tag_id: uuid.UUID,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx)],
) -> None:
    await svc.detach_tag(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        tag_id=tag_id,
    )


@router.post("/{note_id}/attachments", response_model=AttachmentOut)
async def upload_note_attachment(
    note_id: uuid.UUID,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx)],
    file: upload_file_field,
) -> AttachmentOut:
    # Size is enforced BEFORE the bytes are stored (guarded read here +
    # a re-check in the service). Member-level, org-scoped (RLS).
    data = await read_capped(file)
    att = await att_svc.add_attachment(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        filename=file.filename or "file",
        mime_type=file.content_type,
        data=data,
    )
    return att_out(att)


@router.get("/{note_id}/attachments", response_model=list[AttachmentOut])
async def list_note_attachments(
    note_id: uuid.UUID,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx)],
) -> list[AttachmentOut]:
    rows = await att_svc.list_attachments(ctx.session, org_id=ctx.org_id, note_id=note_id)
    return [att_out(r) for r in rows]


@router.patch("/{note_id}", response_model=VersionOut)
async def update_note(
    note_id: uuid.UUID,
    body: NotePatchIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx)],
    edit_session_id: Annotated[str | None, Header(alias="X-Edit-Session-Id")] = None,
) -> VersionOut:
    # task_id is bidirectional Proposal A: pass it through only when the
    # client actually sent the key (an explicit null unlinks; omitting
    # it preserves the link). The service sentinel is "argument absent".
    # ``audio_ref`` uses the same omit-vs-explicit-None semantics so the
    # voice-recorder UX can attach the audio in a separate request after
    # the row exists. We split the call rather than ``**extra`` so mypy
    # can verify each kwarg's type against its sentinel union.
    kwargs: dict[str, Any] = {}
    if "task_id" in body.model_fields_set:
        kwargs["task_id"] = body.task_id
    if "audio_ref" in body.model_fields_set:
        kwargs["audio_ref"] = body.audio_ref
    channel = "web" if edit_session_id else "api"
    v = await svc.update_note(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        expected_version=body.expected_version,
        title=body.title,
        text=body.text,
        channel=channel,
        edit_session_id=edit_session_id,
        **kwargs,
    )
    return VersionOut(id=note_id, version=v)


@router.post("/{note_id}/append", response_model=AppendOut)
async def append_note(
    note_id: uuid.UUID,
    body: NoteAppendIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx)],
) -> AppendOut:
    """Task 4ac39ecf: context-blind append for ``note.summary`` /
    ``note.transcript``. The caller never has to read the body first
    (saves context for MCP / LLM tools). When ``expected_version`` is
    omitted, the helper appends onto whatever state the row currently
    has -- safe for log-style writers."""
    new_version, appended = await svc.append_to_note_field(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        target=body.target,
        text=body.text,
        separator=body.separator,
        expected_version=body.expected_version,
        dedupe_if_tail_matches=body.dedupe_if_tail_matches,
    )
    return AppendOut(id=note_id, version=new_version, appended_chars=appended)


@router.post("/{note_id}/delete", response_model=VersionOut)
async def delete_note(
    note_id: uuid.UUID,
    body: ExpectedVersionIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx)],
) -> VersionOut:
    v = await svc.soft_delete_note(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        expected_version=body.expected_version,
    )
    return VersionOut(id=note_id, version=v)


@router.post("/{note_id}/restore", response_model=VersionOut)
async def restore_note(
    note_id: uuid.UUID,
    body: ExpectedVersionIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx)],
) -> VersionOut:
    v = await svc.restore_note(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        expected_version=body.expected_version,
    )
    return VersionOut(id=note_id, version=v)


@router.post("/{note_id}/archive", response_model=VersionOut)
async def archive_note(
    note_id: uuid.UUID,
    body: ExpectedVersionIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx)],
) -> VersionOut:
    v = await svc.archive_note(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        expected_version=body.expected_version,
        archived=True,
    )
    return VersionOut(id=note_id, version=v)


@router.post("/{note_id}/unarchive", response_model=VersionOut)
async def unarchive_note(
    note_id: uuid.UUID,
    body: ExpectedVersionIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx)],
) -> VersionOut:
    v = await svc.archive_note(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        expected_version=body.expected_version,
        archived=False,
    )
    return VersionOut(id=note_id, version=v)


@router.post("/{note_id}/transcribe", response_model=NoteOut)
async def transcribe(
    note_id: uuid.UUID,
    body: NoteTranscribeIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx)],
) -> NoteOut:
    n = await svc.transcribe(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        operation_id=body.operation_id,
        embed=body.embed,
    )
    pid = await note_links_svc.primary_task_id_for_note(
        ctx.session, org_id=ctx.org_id, note_id=n.id
    )
    return _out(n, primary_task_id=pid)


@router.post("/conversations", response_model=NoteOut)
async def start_conversation(
    body: ConversationStartIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx)],
) -> NoteOut:
    n = await svc.create_note(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        kind=NoteKind.conversation,
        project_id=body.project_id,
        title=body.title,
    )
    return _out(n)


@router.post("/{note_id}/messages", response_model=NoteTurnOut)
async def append_message(
    note_id: uuid.UUID,
    body: AppendMessageIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx)],
) -> NoteTurnOut:
    reply = await svc.append_message(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        content=body.content,
        operation_id=body.operation_id,
    )
    return _turn(reply)


@router.get("/{note_id}/turns", response_model=list[NoteTurnOut])
async def list_turns(
    note_id: uuid.UUID,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx)],
) -> list[NoteTurnOut]:
    rows = await svc.list_turns(ctx.session, org_id=ctx.org_id, note_id=note_id)
    return [_turn(t) for t in rows]


@router.post("/synthesize", response_model=SynthOut)
async def synthesize(
    body: SynthesizeIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx)],
) -> SynthOut:
    res = await svc.synthesize(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        text=body.text,
        operation_id=body.operation_id,
    )
    return SynthOut(audio_ref=res["audio_ref"], model_id=res["model_id"])


@router.post("/command", response_model=NoteOut)
async def command(
    body: CommandIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx)],
) -> NoteOut:
    n = await svc.run_command(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        text=body.text,
    )
    pid = await note_links_svc.primary_task_id_for_note(
        ctx.session, org_id=ctx.org_id, note_id=n.id
    )
    return _out(n, primary_task_id=pid)


@router.post("/{note_id}/erase", response_model=NoteEraseOut)
async def erase(
    note_id: uuid.UUID,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx)],
) -> NoteEraseOut:
    res = await svc.gdpr_erase_note(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
    )
    return NoteEraseOut(
        audio_ref=res.audio_ref,
        memory_blobs_deleted=res.memory_blobs_deleted,
    )


# ----------------------------------------------------------------------
# Quick-create endpoint (Apple Shortcut / Tasker / cURL one-liner).
# Auth: agent_token (``flow_at_...``). The user mints one in
# /settings/ai-assistants, pastes it into the Shortcut. The Shortcut
# resolves the project by case-insensitive partial name (or UUID).
# Designed to be hit from a single ``Get Contents of URL`` action on
# iOS Shortcuts; no JWT, no workspace header, just the bearer.


class QuickCreateIn(BaseModel):
    """Body for the Apple Shortcut / iOS Dictation flow. ``project``
    is a project name (case-insensitive partial match) or a UUID; if
    omitted, the note lands in the default project of the assistant's
    workspace. ``kind`` defaults to ``text`` because dictation is
    text-first; voice notes still go through the /notes flow."""

    project: str | None = Field(default=None, max_length=200)
    text: str = Field(min_length=1, max_length=20000)
    kind: NoteKind = NoteKind.text
    title: str | None = Field(default=None, max_length=300)


class QuickCreateOut(BaseModel):
    id: uuid.UUID
    project_id: uuid.UUID | None
    kind: NoteKind


async def _agent_principal(
    authorization: Annotated[str | None, Header()] = None,
) -> agent_tokens_svc.AuthenticatedAgent:
    """Resolve the ``Authorization: Bearer flow_at_...`` header to an
    ``AuthenticatedAgent``. 401 if missing / malformed / unknown.
    Mirrors the MCP HTTP transport bearer middleware (mcp/server_http)
    but at the FastAPI dep boundary so this endpoint can be reached
    from the regular ingress without going through /mcp."""
    if not authorization or not authorization.lower().startswith("bearer "):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Missing or malformed Authorization header",
        )
    raw = authorization.split(" ", 1)[1].strip()
    if not agent_tokens_svc.is_agent_token(raw):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Bearer is not a Flow agent token",
        )
    principal = await agent_tokens_svc.authenticate(raw)
    if principal is None:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Unknown / revoked / expired token",
        )
    return principal


async def _resolve_project(org_id: uuid.UUID, needle: str | None) -> uuid.UUID | None:
    """``needle`` may be a UUID (exact match), a project name (exact,
    case-insensitive), or a substring (case-insensitive partial). The
    first matching project tag wins; absent project yields ``None``
    (create_note falls back to the default ``General`` project)."""
    if not needle:
        return None
    try:
        return uuid.UUID(needle)
    except ValueError:
        pass
    async with admin_session() as session:
        # Set the org GUC so RLS lets us see the tags.
        from sqlalchemy import text as sql_text

        await session.execute(
            sql_text("SELECT set_config('app.current_org', :o, true)"),
            {"o": str(org_id)},
        )
        # Exact case-insensitive first; partial as fallback.
        exact = (
            await session.execute(
                select(Tag.id)
                .join(ProjectProfile, ProjectProfile.tag_id == Tag.id)
                .where(Tag.kind == TagKind.project)
                .where(Tag.name.ilike(needle))
                .limit(1)
            )
        ).scalar_one_or_none()
        if exact:
            return exact
        partial = (
            await session.execute(
                select(Tag.id)
                .join(ProjectProfile, ProjectProfile.tag_id == Tag.id)
                .where(Tag.kind == TagKind.project)
                .where(Tag.name.ilike(f"%{needle}%"))
                .limit(1)
            )
        ).scalar_one_or_none()
        return partial


@router.post("/quick-create", response_model=QuickCreateOut)
async def quick_create(
    body: QuickCreateIn,
    principal: Annotated[agent_tokens_svc.AuthenticatedAgent, Depends(_agent_principal)],
) -> QuickCreateOut:
    """Single-shot note creation for Apple Shortcuts, Tasker, or any
    one-liner client. The agent token's bound user becomes the actor.
    Resolves ``project`` to a project tag; creates the note via
    ``services/notes.create_note``."""
    project_id = await _resolve_project(principal.org_id, body.project)
    async with admin_session() as session:
        from sqlalchemy import text as sql_text

        await session.execute(
            sql_text("SELECT set_config('app.current_org', :o, true)"),
            {"o": str(principal.org_id)},
        )
        await session.execute(
            sql_text("SELECT set_config('app.current_user', :u, true)"),
            {"u": str(principal.user_id)},
        )
        note = await svc.create_note(
            session,
            org_id=principal.org_id,
            actor_id=principal.user_id,
            kind=body.kind,
            text=body.text,
            title=body.title,
            project_id=project_id,
        )
        await session.commit()
    return QuickCreateOut(id=note.id, project_id=note.project_id, kind=note.kind)


# ---------------------------------------------------------------------------
# Garden ecosystem (docs/adr/0029 P1) endpoints. Set maturity, promote,
# derive a fruit task, link notes to notes/tasks. Tags every endpoint
# with "garden" so the OpenAPI surface stays grouped.
# ---------------------------------------------------------------------------


@router.post(
    "/{note_id}/maturity",
    response_model=NoteOut,
    tags=["garden"],
)
async def set_note_maturity(
    note_id: uuid.UUID,
    body: NoteSetMaturityIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx)],
) -> NoteOut:
    n = await note_links_svc.set_maturity(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        maturity=body.maturity,
    )
    tagmap = await svc.tags_by_note(ctx.session, note_ids=[n.id])
    pid = await note_links_svc.primary_task_id_for_note(
        ctx.session, org_id=ctx.org_id, note_id=n.id
    )
    return _out(n, tagmap.get(n.id, []), primary_task_id=pid)


@router.post(
    "/{note_id}/promote",
    response_model=DerivedTaskOut,
    tags=["garden"],
)
async def promote_note(
    note_id: uuid.UUID,
    body: NotePromoteIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx)],
) -> DerivedTaskOut:
    task, link = await note_links_svc.promote_note_to_task(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        title=body.title,
    )
    return DerivedTaskOut(task_id=task.id, link=_task_link_out(link))


@router.post(
    "/{note_id}/derive-task",
    response_model=DerivedTaskOut,
    tags=["garden"],
)
async def derive_task(
    note_id: uuid.UUID,
    body: NoteDeriveTaskIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx)],
) -> DerivedTaskOut:
    task, link = await note_links_svc.derive_task_from_note(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        title=body.title,
        description=body.description,
        estimate_effort_h=body.estimate_effort_h,
        extra_tag_ids=list(body.extra_tag_ids),
    )
    return DerivedTaskOut(task_id=task.id, link=_task_link_out(link))


@router.post(
    "/{note_id}/links",
    response_model=NoteLinkOut,
    tags=["garden"],
)
async def link_notes(
    note_id: uuid.UUID,
    body: NoteLinkIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx)],
) -> NoteLinkOut:
    # ``note_id`` from the URL is the parent (the link's "from"); the
    # body carries the child and the kind. We accept the parent in
    # both places defensively.
    if body.parent_note_id != note_id:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST)
    link = await note_links_svc.link_notes(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        parent_note_id=body.parent_note_id,
        child_note_id=body.child_note_id,
        kind=body.kind,
    )
    return _link_out(link)


@router.delete(
    "/{note_id}/links",
    status_code=204,
    tags=["garden"],
)
async def unlink_notes(
    note_id: uuid.UUID,
    child_note_id: uuid.UUID,
    kind: str,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx)],
) -> None:
    removed = await note_links_svc.unlink_notes(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        parent_note_id=note_id,
        child_note_id=child_note_id,
        kind=kind,
    )
    if not removed:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND)


@router.get(
    "/{note_id}/links",
    response_model=NoteWithLinksOut,
    tags=["garden"],
)
async def list_note_links(
    note_id: uuid.UUID,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx)],
) -> NoteWithLinksOut:
    n = await svc.get_note(ctx.session, org_id=ctx.org_id, note_id=note_id)
    tagmap = await svc.tags_by_note(ctx.session, note_ids=[n.id])
    outgoing, incoming = await note_links_svc.list_note_links(
        ctx.session, org_id=ctx.org_id, note_id=note_id
    )
    task_links = await note_links_svc.list_note_task_links(
        ctx.session, org_id=ctx.org_id, note_id=note_id
    )
    pid = await note_links_svc.primary_task_id_for_note(
        ctx.session, org_id=ctx.org_id, note_id=n.id
    )
    return NoteWithLinksOut(
        note=_out(n, tagmap.get(n.id, []), primary_task_id=pid),
        outgoing=[_link_out(o) for o in outgoing],
        incoming=[_link_out(o) for o in incoming],
        task_links=[_task_link_out(o) for o in task_links],
    )


@router.post(
    "/{note_id}/task-links",
    response_model=NoteTaskLinkOut,
    tags=["garden"],
)
async def add_note_task_link(
    note_id: uuid.UUID,
    body: NoteTaskLinkIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx)],
) -> NoteTaskLinkOut:
    """Create a typed note↔task link from the note side. ``kind`` picks
    the named operation: ``subject`` → start_task_on_note,
    ``artifact`` → record_task_artifact. ``derived_from`` and
    ``promoted_from`` are intentionally NOT accepted here: those are
    creation-with-link operations, not free linkage (see
    /notes/{id}/derive-task and /promote)."""
    if body.kind == "subject":
        link = await note_links_svc.start_task_on_note(
            ctx.session,
            org_id=ctx.org_id,
            actor_id=ctx.user_id,
            task_id=body.task_id,
            note_id=note_id,
        )
    elif body.kind == "artifact":
        link = await note_links_svc.record_task_artifact(
            ctx.session,
            org_id=ctx.org_id,
            actor_id=ctx.user_id,
            task_id=body.task_id,
            note_id=note_id,
        )
    else:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST)
    return _task_link_out(link)


@router.delete(
    "/{note_id}/task-links",
    status_code=204,
    tags=["garden"],
)
async def remove_note_task_link(
    note_id: uuid.UUID,
    task_id: uuid.UUID,
    kind: str,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx)],
) -> None:
    """Idempotent removal: returns 404 only if no row matched. Refuses
    ``promoted_from`` (a transplant cannot be undone via unlink; the
    note has ``promoted_at`` set as a side-effect)."""
    removed = await note_links_svc.unlink_note_task(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        task_id=task_id,
        kind=kind,
    )
    if not removed:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND)


def _revision_out(rev: Any) -> RevisionOut:
    """Serialize an EntityRevision ORM row. ``org_id`` is dropped: the
    revision lives in the caller's tenant already (RLS)."""
    return RevisionOut(
        id=rev.id,
        entity_kind=rev.entity_kind,
        entity_id=rev.entity_id,
        snapshot=rev.snapshot or {},
        changed_fields=list(rev.changed_fields or []),
        channel=rev.channel,
        actor_id=rev.actor_id,
        actor_kind=rev.actor_kind,
        actor_subject_id=rev.actor_subject_id,
        edit_session_id=rev.edit_session_id,
        version_from=rev.version_from,
        version_to=rev.version_to,
        edit_count=rev.edit_count,
        started_at=rev.started_at,
        last_edit_at=rev.last_edit_at,
        sealed_at=rev.sealed_at,
        restored_from=rev.restored_from,
        summary=rev.summary,
    )


@router.get("/{note_id}/revisions", response_model=list[RevisionOut])
async def list_note_revisions(
    note_id: uuid.UUID,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx)],
    limit: Annotated[int, Query(ge=1, le=200)] = 50,
    before: Annotated[datetime.datetime | None, Query()] = None,
) -> list[RevisionOut]:
    """Timeline of revisions for this note, most recent first."""
    await svc.get_note(ctx.session, org_id=ctx.org_id, note_id=note_id, include_deleted=True)
    rows = await rev_svc.list_revisions(
        ctx.session,
        entity_kind=rev_svc.ENTITY_KIND_NOTE,
        entity_id=note_id,
        limit=limit,
        before=before,
    )
    return [_revision_out(r) for r in rows]


@router.get("/{note_id}/revisions/{rev_id}", response_model=RevisionOut)
async def get_note_revision(
    note_id: uuid.UUID,
    rev_id: uuid.UUID,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx)],
) -> RevisionOut:
    rev = await rev_svc.get_revision(
        ctx.session,
        revision_id=rev_id,
        entity_kind=rev_svc.ENTITY_KIND_NOTE,
        entity_id=note_id,
    )
    return _revision_out(rev)


@router.patch("/{note_id}/revisions/{rev_id}", response_model=RevisionOut)
async def update_note_revision_summary(
    note_id: uuid.UUID,
    rev_id: uuid.UUID,
    body: RevisionSummaryIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx)],
) -> RevisionOut:
    """Set / clear the ``summary`` label on a revision. Mirror of the
    /tasks endpoint; see that one for the contract."""
    rev = await rev_svc.set_summary(
        ctx.session,
        revision_id=rev_id,
        summary=body.summary,
        entity_kind=rev_svc.ENTITY_KIND_NOTE,
        entity_id=note_id,
    )
    return _revision_out(rev)


@router.post("/{note_id}/revisions/{rev_id}/restore", response_model=VersionOut)
async def restore_note_revision(
    note_id: uuid.UUID,
    rev_id: uuid.UUID,
    body: RevisionRestoreIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx)],
) -> VersionOut:
    """Apply the snapshot's restorable fields (``title`` /
    ``transcript``) back to the note. Logged as a NEW sealed
    revision on the ``restore`` channel with ``restored_from``."""
    version = await svc.restore_revision(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        revision_id=rev_id,
        expected_version=body.expected_version,
        fields=body.fields,
    )
    return VersionOut(id=note_id, version=version)


@router.post("/{note_id}/edit-session/seal", response_model=EditSessionSealOut)
async def seal_note_edit_session(
    note_id: uuid.UUID,
    body: EditSessionSealIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx)],
) -> EditSessionSealOut:
    count = await rev_svc.seal_open(
        ctx.session,
        entity_kind=rev_svc.ENTITY_KIND_NOTE,
        entity_id=note_id,
        actor_id=ctx.user_id,
        edit_session_id=body.edit_session_id,
    )
    return EditSessionSealOut(sealed=count)
