// The palette, extracted from the app rather than copied.
//
// The app's stylesheet is nearly seven thousand lines and the part that
// matters here is about forty: three blocks of custom properties. Copying
// them by hand produces two palettes that agree today; extracting them
// produces one palette with two readers, and a check that fails when they
// stop agreeing.
//
// A free result falls out of doing it this way. The app defines its dark
// palette TWICE -- once for an explicit choice and once for the system
// preference -- kept in step by a comment. This extractor compares them
// and refuses when they differ, which turns that comment into a gate for
// the app as well as for the extension.

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const SOURCE = join(ROOT, '..', 'web', 'src', 'index.css')
const TARGET = join(ROOT, 'src', 'styles', 'tokens.generated.css')

const LIGHT = ':root'
const DARK_EXPLICIT = ":root[data-theme='dark']"
const DARK_SYSTEM = ":root:not([data-theme='light']):not([data-theme='dark'])"

/** The custom properties of the first block whose selector matches.
 *  @param {string} css @param {string} selector @returns {Map<string,string>} */
function propertiesOf(css, selector) {
  const at = css.indexOf(selector)
  if (at === -1) throw new Error(`selector not found in web/src/index.css: ${selector}`)
  const open = css.indexOf('{', at)
  const close = css.indexOf('}', open)
  if (open === -1 || close === -1) throw new Error(`unterminated block for ${selector}`)
  /** @type {Map<string,string>} */
  const out = new Map()
  for (const line of css.slice(open + 1, close).split('\n')) {
    const match = /^\s*(--[a-z0-9-]+)\s*:\s*([^;]+);/i.exec(line)
    const name = match?.[1]
    const value = match?.[2]
    if (name && value) out.set(name, value.trim())
  }
  if (out.size === 0) throw new Error(`no custom properties under ${selector}`)
  return out
}

/** @param {Map<string,string>} props @returns {string} */
function render(props) {
  return [...props].map(([name, value]) => `  ${name}: ${value};`).join('\n')
}

const css = readFileSync(SOURCE, 'utf8')
const light = propertiesOf(css, LIGHT)
const darkExplicit = propertiesOf(css, DARK_EXPLICIT)
const darkSystem = propertiesOf(css, DARK_SYSTEM)

const drift = [...darkExplicit]
  .filter(([name, value]) => darkSystem.get(name) !== value)
  .concat([...darkSystem].filter(([name]) => !darkExplicit.has(name)))
if (drift.length > 0) {
  console.error(
    `\nweb/src/index.css: the two dark palettes disagree on ${drift.length} property(ies):\n`,
  )
  for (const [name] of drift) {
    console.error(`  ${name}\n      explicit: ${darkExplicit.get(name) ?? '(absent)'}`)
    console.error(`      system:   ${darkSystem.get(name) ?? '(absent)'}`)
  }
  console.error(
    '\nOne is the palette a reader gets after choosing dark, the other the\n' +
      'palette a reader gets for choosing nothing. A property in one and not\n' +
      'the other is a colour that changes when you touch the theme toggle.\n',
  )
  process.exit(1)
}

const generated = `/* GENERATED by extension/scripts/gen-tokens.mjs from web/src/index.css.
   Do not edit: run "pnpm gen:tokens". The token NAMES are the app's own,
   so a rule copied between the two codebases means the same thing in
   both. Spacing is not here -- the app has no spacing tokens, and a
   420px panel needs a denser scale than a full page, so the extension
   defines its own under a --myc- prefix in base.css. */

:root {
${render(light)}
}

:root[data-theme='dark'] {
${render(darkExplicit)}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']):not([data-theme='dark']) {
${render(darkSystem)
  .split('\n')
  .map((line) => `  ${line}`)
  .join('\n')}
  }
}
`

if (process.argv.includes('--check')) {
  /** @type {string} */
  let current
  try {
    current = readFileSync(TARGET, 'utf8')
  } catch {
    // Never generated, so it is out of date by definition.
    current = ''
  }
  if (current !== generated) {
    console.error(
      '\nextension/src/styles/tokens.generated.css is out of date with\n' +
        'web/src/index.css. Run "pnpm gen:tokens".\n',
    )
    process.exit(1)
  }
  console.log(`tokens: ${light.size} properties, in step with web/src/index.css.`)
} else {
  writeFileSync(TARGET, generated)
  console.log(`tokens: wrote ${light.size} properties to src/styles/tokens.generated.css`)
}
