"""Italian province codes (sigle) for FatturaPA ``Provincia`` validation.

The FatturaPA XSD only constrains ``Provincia`` to ``[A-Z]{2}``; SdI rejects a
well-formed-but-nonexistent code (e.g. ``XX``). Validating against the real
list (only when the country is IT) catches that before transmission. The set
includes the current 107 provinces + ``SU`` (Sud Sardegna) and the recently
abolished Sardinian codes (``CI``/``OG``/``OT``/``VS``), which may still appear
in older anagraphic data, to avoid false rejections.
"""

from __future__ import annotations

IT_PROVINCES: frozenset[str] = frozenset(
    {
        "AG",
        "AL",
        "AN",
        "AO",
        "AP",
        "AQ",
        "AR",
        "AT",
        "AV",
        "BA",
        "BG",
        "BI",
        "BL",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BZ",
        "CA",
        "CB",
        "CE",
        "CH",
        "CI",
        "CL",
        "CN",
        "CO",
        "CR",
        "CS",
        "CT",
        "CZ",
        "EN",
        "FC",
        "FE",
        "FG",
        "FI",
        "FM",
        "FR",
        "GE",
        "GO",
        "GR",
        "IM",
        "IS",
        "KR",
        "LC",
        "LE",
        "LI",
        "LO",
        "LT",
        "LU",
        "MB",
        "MC",
        "ME",
        "MI",
        "MN",
        "MO",
        "MS",
        "MT",
        "NA",
        "NO",
        "NU",
        "OG",
        "OR",
        "OT",
        "PA",
        "PC",
        "PD",
        "PE",
        "PG",
        "PI",
        "PN",
        "PO",
        "PR",
        "PT",
        "PU",
        "PV",
        "PZ",
        "RA",
        "RC",
        "RE",
        "RG",
        "RI",
        "RM",
        "RN",
        "RO",
        "SA",
        "SI",
        "SO",
        "SP",
        "SR",
        "SS",
        "SU",
        "SV",
        "TA",
        "TE",
        "TN",
        "TO",
        "TP",
        "TR",
        "TS",
        "TV",
        "UD",
        "VA",
        "VB",
        "VC",
        "VE",
        "VI",
        "VR",
        "VS",
        "VT",
        "VV",
    }
)


def is_valid_provincia(sigla: str | None, country: str | None) -> bool:
    """True unless ``sigla`` is a non-empty code that is not a real Italian
    province while the country is IT. Empty/absent (the field is optional) and
    foreign-country values are accepted here (validated elsewhere/not emitted)."""
    if not sigla or (country or "IT").upper() != "IT":
        return True
    return sigla.upper() in IT_PROVINCES
