"""Notes / conversation / canonical-intent router. Thin adapter
(docs/adr/0001, 0020, 0021, FR-16). Capture is unmetered; STT/LLM/TTS
processing is metered in the service. Providers are injected via the
seam (fakes in tests)."""

from __future__ import annotations

import datetime
import uuid
from typing import Annotated, Any

from fastapi import APIRouter, Depends, Header, HTTPException, Query, Request, Response, status
from pydantic import BaseModel, Field
from sqlalchemy import select

from mycelium_api.deps import (
    TenantCtx,
    current_claims,
    note_attachment_write_ctx,
    part_body_patch_ctx,
    part_body_read_ctx,
    part_body_write_ctx,
    require_agent_scope,
    tenant_ctx,
)
from mycelium_api.routers.attachments import att_out, read_capped, upload_file_field
from mycelium_api.routers.tags import require_tag_kind
from mycelium_api.schemas import (
    AppendMessageIn,
    AppendOut,
    AttachmentOut,
    CommandIn,
    ConversationStartIn,
    DerivedTaskOut,
    DistillationOut,
    EditSessionSealIn,
    EditSessionSealOut,
    ExpectedVersionIn,
    NoteAppendIn,
    NoteCreateIn,
    NoteDeriveTaskIn,
    NoteEraseOut,
    NoteLinkIn,
    NoteLinkOut,
    NoteMergeIn,
    NoteOut,
    NotePartAppendIn,
    NotePartCreateIn,
    NotePartOut,
    NotePartPatchIn,
    NotePartPrependIn,
    NotePartReorderIn,
    NotePartReplaceIn,
    NotePartTrashOut,
    NotePartUIStateIn,
    NotePatchIn,
    NotePromoteIn,
    NoteSetMaturityIn,
    NoteTagIn,
    NoteTaskLinkIn,
    NoteTaskLinkOut,
    NoteTranscribeIn,
    NoteTurnOut,
    NoteWithLinksOut,
    ReplaceOut,
    RevisionOut,
    RevisionRestoreIn,
    RevisionSummaryIn,
    SynthesizeIn,
    SynthOut,
    TagBrief,
    TaskChecklistClearDoneOut,
    TaskChecklistItemCreateIn,
    TaskChecklistItemOut,
    TaskChecklistItemPatchIn,
    TaskChecklistReorderIn,
    VersionOut,
)
from mycelium_api.textstream import read_capped_text, read_patch_payload, text_block_headers
from mycelium_core.config import get_settings
from mycelium_core.db import admin_session
from mycelium_core.errors import DomainError
from mycelium_core.i18n import MessageCode
from mycelium_core.models.note import Note, NoteKind, NoteTurn
from mycelium_core.models.project_profile import ProjectProfile
from mycelium_core.models.tag import Tag, TagKind
from mycelium_core.models.task_checklist_item import TaskChecklistItem
from mycelium_core.services import agent_tokens as agent_tokens_svc
from mycelium_core.services import attachments as att_svc
from mycelium_core.services import capability_tokens as capability_tokens_svc
from mycelium_core.services import decomposition as decomposition_svc
from mycelium_core.services import entity_revisions as rev_svc
from mycelium_core.services import note_links as note_links_svc
from mycelium_core.services import note_parts as parts_svc
from mycelium_core.services import notes as svc
from mycelium_core.services import task_checklist as checklist_svc

router = APIRouter(prefix="/notes", tags=["notes"])


def _brief(tag: Tag) -> TagBrief:
    return TagBrief(id=tag.id, kind=tag.kind, name=tag.name, color=tag.color)


def _part_out(p: Any, *, ui_collapsed: bool = False) -> NotePartOut:
    """Project a NotePart ORM row to the schema. ``ui_collapsed`` is
    user-scoped state from note_part_ui_state; default false (no row
    materialised means expanded)."""
    return NotePartOut(
        id=p.id,
        note_id=p.note_id,
        ord=p.ord,
        title=getattr(p, "title", None),
        body=p.body or "",
        lang=p.lang,
        merged_from_note_id=p.merged_from_note_id,
        version=p.version,
        ui_collapsed=ui_collapsed,
    )


def _derived_transcript(
    parts: list[NotePartOut] | None,
    explicit: str | None,
) -> str | None:
    """Phase 6 final: ``NoteOut.transcript`` is derived. When the
    caller already has the parts list at hand we join part bodies by
    a blank line; otherwise the caller passes an explicit body
    (single-row paths that didn't bother loading parts). Empty parts
    + no override returns ``None`` so the SPA / clients still see
    null-vs-empty distinguished."""
    if parts is not None and parts:
        return "\n\n".join((p.body or "") for p in parts)
    return explicit


def _out(
    n: Note,
    tags: list[Tag] | None = None,
    primary_task_id: uuid.UUID | None = None,
    task_title: str | None = None,
    derived_task_ids: list[uuid.UUID] | None = None,
    linked_task_count: int = 0,
    parts: list[NotePartOut] | None = None,
    transcript: str | None = None,
) -> NoteOut:
    # docs/adr/0029 P3: ``task_id`` exposed in the API is derived
    # from the typed link table (primary_task_id_for_note). Callers
    # batch-load the map for list endpoints; the single-note path
    # may pass the value explicitly. ``derived_task_ids`` is the full
    # list of tasks generated by the note (derived_from + promoted_from),
    # used by the SPA's "N tasks" chip on the note row.
    # ``linked_task_count`` (task 1e07437e) is the total of typed
    # links across every kind (subject, artifact, derived_from,
    # promoted_from); the chip now reflects this so subject/artifact-
    # only links also surface.
    # Migration 0016: ``project_id`` is derived from the project-kind
    # tag in ``tags`` (junction is the source of truth, like tasks).
    project_id = next(
        (t.id for t in (tags or []) if getattr(t.kind, "value", t.kind) == "project"),
        None,
    )
    return NoteOut(
        id=n.id,
        project_id=project_id,
        task_id=primary_task_id,
        task_title=task_title,
        kind=n.kind,
        status=n.status,
        title=n.title,
        # Phase 6 final: ``transcript`` is derived from the parts list
        # when the caller has it loaded; otherwise the caller can
        # pass an explicit value (single-row paths that skipped the
        # parts join). The legacy column is gone in migration 0012.
        transcript=_derived_transcript(parts, transcript),
        summary=n.summary,
        audio_ref=n.audio_ref,
        audio_seconds=n.audio_seconds,
        is_archived=n.is_archived,
        protected=n.protected,
        deleted_at=n.deleted_at,
        tags=[_brief(t) for t in (tags or [])],
        version=n.version,
        maturity=n.maturity,
        promoted_at=n.promoted_at,
        humus_kind=n.humus_kind,
        derived_task_ids=list(derived_task_ids or []),
        linked_task_count=linked_task_count,
        parts=list(parts or []),
    )


def _link_out(link: Any) -> NoteLinkOut:
    return NoteLinkOut(
        id=link.id,
        parent_note_id=link.parent_note_id,
        child_note_id=link.child_note_id,
        kind=link.kind,
        created_by=link.created_by,
        created_at=link.created_at,
    )


def _task_link_out(link: Any) -> NoteTaskLinkOut:
    return NoteTaskLinkOut(
        id=link.id,
        note_id=link.note_id,
        task_id=link.task_id,
        kind=link.kind,
        created_by=link.created_by,
        created_at=link.created_at,
    )


def _turn(t: NoteTurn) -> NoteTurnOut:
    return NoteTurnOut(id=t.id, role=t.role, content=t.content, ord=t.ord)


@router.post("", response_model=NoteOut)
async def create_note(
    body: NoteCreateIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> NoteOut:
    n = await svc.create_note(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        kind=body.kind,
        # ``project_id`` reaches the choke-point as the named
        # ``project_tag_id`` (services/tag_assignment), so its kind is
        # checked there -- a client id passed here is a 400, not a
        # silently mis-filed project.
        project_id=body.project_tag_id,
        title=body.title,
        text=body.text,
        audio_ref=body.audio_ref,
        audio_seconds=body.audio_seconds,
    )
    if body.client_tag_id is not None:
        # create_note derives the client from the project, or falls back
        # to the workspace default when there is none (docs/adr/0021).
        # Naming a client is the only way to say which perimeter a
        # projectless note belongs to; a client that contradicts the
        # project is refused here (TAG_CLIENT_PROJECT_MISMATCH) and the
        # whole create rolls back with it.
        await require_tag_kind(
            ctx.session, org_id=ctx.org_id, tag_id=body.client_tag_id, kind=TagKind.client
        )
        await svc.attach_tag(
            ctx.session,
            org_id=ctx.org_id,
            actor_id=ctx.user_id,
            note_id=n.id,
            tag_id=body.client_tag_id,
        )
    # Return the note with its tags: create() enforces a client
    # (default "Personal"), so the response must reflect it.
    tagmap = await svc.tags_by_note(ctx.session, note_ids=[n.id])
    pid = await note_links_svc.primary_task_id_for_note(
        ctx.session, org_id=ctx.org_id, note_id=n.id
    )
    derived = await note_links_svc.derived_task_ids_for_notes(
        ctx.session, org_id=ctx.org_id, note_ids=[n.id]
    )
    titles = await note_links_svc.task_titles_for_ids(
        ctx.session, org_id=ctx.org_id, task_ids=[pid] if pid else []
    )
    return _out(
        n,
        tagmap.get(n.id, []),
        primary_task_id=pid,
        task_title=titles.get(pid) if pid else None,
        derived_task_ids=derived.get(n.id, []),
        transcript=await svc.get_body(ctx.session, note_id=n.id),
    )


@router.get(
    "/links",
    response_model=list[NoteLinkOut],
    tags=["garden"],
)
async def list_workspace_note_links(
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> list[NoteLinkOut]:
    # Garden mindmap (ADR-0029 P2): single round-trip for the full
    # edge set in the workspace. Declared before ``GET /{note_id}``
    # because that catch-all would otherwise capture "links" as a
    # ``note_id`` path parameter and fail UUID validation with 422.
    rows = await note_links_svc.list_workspace_note_links(ctx.session, org_id=ctx.org_id)
    return [_link_out(r) for r in rows]


@router.get("", response_model=list[NoteOut])
async def list_notes(
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
    include_archived: bool = False,
    include_deleted: bool = False,
    project_id: uuid.UUID | None = None,
    tag_id: uuid.UUID | None = None,
    q: str | None = None,
) -> list[NoteOut]:
    rows = await svc.list_notes(
        ctx.session,
        org_id=ctx.org_id,
        include_archived=include_archived,
        include_deleted=include_deleted,
        project_id=project_id,
        tag_id=tag_id,
        q=q,
    )
    ids = [n.id for n in rows]
    tagmap = await svc.tags_by_note(ctx.session, note_ids=ids)
    pid_map = await note_links_svc.primary_task_ids_for_notes(
        ctx.session, org_id=ctx.org_id, note_ids=ids
    )
    derived_map = await note_links_svc.derived_task_ids_for_notes(
        ctx.session, org_id=ctx.org_id, note_ids=ids
    )
    count_map = await note_links_svc.linked_task_counts_for_notes(
        ctx.session, org_id=ctx.org_id, note_ids=ids
    )
    title_map = await note_links_svc.task_titles_for_ids(
        ctx.session, org_id=ctx.org_id, task_ids=list(pid_map.values())
    )
    # Phase 6 final: ``transcript`` on the API is derived from
    # note_part(ord=0)+ joined. One batched query keeps the list
    # endpoint a single round-trip.
    bodies = await svc._bodies_by_note(ctx.session, note_ids=ids)
    return [
        _out(
            n,
            tagmap.get(n.id, []),
            primary_task_id=(pid := pid_map.get(n.id)),
            task_title=title_map.get(pid) if pid else None,
            derived_task_ids=derived_map.get(n.id, []),
            linked_task_count=count_map.get(n.id, 0),
            transcript=bodies.get(n.id),
        )
        for n in rows
    ]


@router.get("/{note_id}", response_model=NoteOut)
async def get_note(
    note_id: uuid.UUID,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> NoteOut:
    n = await svc.get_note(ctx.session, org_id=ctx.org_id, note_id=note_id)
    tagmap = await svc.tags_by_note(ctx.session, note_ids=[n.id])
    pid = await note_links_svc.primary_task_id_for_note(
        ctx.session, org_id=ctx.org_id, note_id=n.id
    )
    derived = await note_links_svc.derived_task_ids_for_notes(
        ctx.session, org_id=ctx.org_id, note_ids=[n.id]
    )
    counts = await note_links_svc.linked_task_counts_for_notes(
        ctx.session, org_id=ctx.org_id, note_ids=[n.id]
    )
    titles = await note_links_svc.task_titles_for_ids(
        ctx.session, org_id=ctx.org_id, task_ids=[pid] if pid else []
    )
    # Phase 2a: GET /notes/{id} includes the ordered parts plus the
    # caller's per-part collapse state. List endpoints leave parts
    # empty for payload economy; the single-note path is the canonical
    # surface for the SPA editor that needs every block.
    parts_rows = await parts_svc.list_parts(ctx.session, org_id=ctx.org_id, note_id=n.id)
    ui = await parts_svc.get_ui_states_for_user(ctx.session, user_id=ctx.user_id, note_id=n.id)
    parts = [_part_out(p, ui_collapsed=ui.get(p.id, False)) for p in parts_rows]
    return _out(
        n,
        tagmap.get(n.id, []),
        primary_task_id=pid,
        task_title=titles.get(pid) if pid else None,
        derived_task_ids=derived.get(n.id, []),
        linked_task_count=counts.get(n.id, 0),
        parts=parts,
    )


@router.post("/{note_id}/distill", response_model=DistillationOut)
async def distill_note(
    note_id: uuid.UUID,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> DistillationOut:
    """Fungal decomposition (ADR-0034, task 4a718dc4): distil the note's
    body into a reusable atom note and flag both as humus so the LLM
    walk can surface them as fertiliser. Idempotent: a note already
    distilled returns its existing distillation untouched (``created``
    False). Member role required; metered LLM call inside the service."""
    res = await decomposition_svc.distill_note(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
    )
    return DistillationOut(
        source_note_id=note_id,
        distilled_note_id=res.distilled_note_id,
        model_id=res.model_id,
        created=res.created,
    )


def _checklist_item_out(it: TaskChecklistItem) -> TaskChecklistItemOut:
    return TaskChecklistItemOut(
        id=it.id,
        task_id=it.task_id,
        note_id=it.note_id,
        text=it.text,
        body=it.body,
        done=it.done,
        position=it.position,
        done_at=it.done_at,
        done_by=it.done_by,
        created_by=it.created_by,
        created_at=it.created_at,
        updated_at=it.updated_at,
        version=it.version,
    )


@router.get("/{note_id}/checklist", response_model=list[TaskChecklistItemOut])
async def list_note_checklist(
    note_id: uuid.UUID,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> list[TaskChecklistItemOut]:
    """A note's checklist (task bae178d2): same shape and widget as the
    task checklist. Items may carry an optional markdown ``body``."""
    rows = await checklist_svc.list_items(ctx.session, org_id=ctx.org_id, note_id=note_id)
    return [_checklist_item_out(r) for r in rows]


@router.post(
    "/{note_id}/checklist",
    response_model=TaskChecklistItemOut,
    status_code=status.HTTP_201_CREATED,
)
async def add_note_checklist_item(
    note_id: uuid.UUID,
    body: TaskChecklistItemCreateIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> TaskChecklistItemOut:
    item = await checklist_svc.add_item(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        text=body.text,
        body=body.body,
        position=body.position,
    )
    return _checklist_item_out(item)


@router.patch("/{note_id}/checklist/{item_id}", response_model=TaskChecklistItemOut)
async def update_note_checklist_item(
    note_id: uuid.UUID,
    item_id: uuid.UUID,
    body: TaskChecklistItemPatchIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> TaskChecklistItemOut:
    item = await checklist_svc.update_item(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        item_id=item_id,
        expected_version=body.expected_version,
        text=body.text,
        body=body.body,
        done=body.done,
        position=body.position,
    )
    return _checklist_item_out(item)


@router.delete("/{note_id}/checklist/{item_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_note_checklist_item(
    note_id: uuid.UUID,
    item_id: uuid.UUID,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> None:
    await checklist_svc.delete_item(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        item_id=item_id,
    )


@router.post("/{note_id}/checklist:clear_done", response_model=TaskChecklistClearDoneOut)
async def clear_note_checklist_done(
    note_id: uuid.UUID,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> TaskChecklistClearDoneOut:
    removed = await checklist_svc.clear_done(
        ctx.session, org_id=ctx.org_id, actor_id=ctx.user_id, note_id=note_id
    )
    return TaskChecklistClearDoneOut(removed=removed)


@router.post("/{note_id}/checklist:reorder", response_model=list[TaskChecklistItemOut])
async def reorder_note_checklist(
    note_id: uuid.UUID,
    body: TaskChecklistReorderIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> list[TaskChecklistItemOut]:
    rows = await checklist_svc.reorder_items(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        ordered_ids=body.ids,
    )
    return [_checklist_item_out(r) for r in rows]


@router.post("/{note_id}/tags", status_code=204)
async def attach_note_tag(
    note_id: uuid.UUID,
    body: NoteTagIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> None:
    await svc.attach_tag(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        tag_id=body.tag_id,
    )


@router.delete("/{note_id}/tags/{tag_id}", status_code=204)
async def detach_note_tag(
    note_id: uuid.UUID,
    tag_id: uuid.UUID,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> None:
    await svc.detach_tag(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        tag_id=tag_id,
    )


@router.post("/{note_id}/attachments", response_model=AttachmentOut)
async def upload_note_attachment(
    note_id: uuid.UUID,
    ctx: Annotated[TenantCtx, Depends(note_attachment_write_ctx, scope="function")],
    file: upload_file_field,
) -> AttachmentOut:
    # Size is enforced BEFORE the bytes are stored (guarded read here +
    # a re-check in the service), against the workspace's effective cap.
    # Member-level, org-scoped (RLS). Auth accepts a normal bearer or a
    # single-use ``attachment:write`` capability scoped to this note
    # (minted by the MCP ``upload_attachment_capability`` tool), consumed
    # on success. Backend-agnostic: ``add_attachment`` works on the default
    # ``pg`` store, so no S3 is required.
    data = await read_capped(file, ctx)
    att = await att_svc.add_attachment(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        filename=file.filename or "file",
        mime_type=file.content_type,
        data=data,
    )
    if ctx.capability_token_id is not None:
        await capability_tokens_svc.consume(ctx.session, token_id=ctx.capability_token_id)
    return att_out(att)


@router.get("/{note_id}/attachments", response_model=list[AttachmentOut])
async def list_note_attachments(
    note_id: uuid.UUID,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> list[AttachmentOut]:
    rows = await att_svc.list_attachments(ctx.session, org_id=ctx.org_id, note_id=note_id)
    return [att_out(r) for r in rows]


@router.patch("/{note_id}", response_model=VersionOut)
async def update_note(
    note_id: uuid.UUID,
    body: NotePatchIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
    edit_session_id: Annotated[str | None, Header(alias="X-Edit-Session-Id")] = None,
) -> VersionOut:
    # task_id is bidirectional Proposal A: pass it through only when the
    # client actually sent the key (an explicit null unlinks; omitting
    # it preserves the link). The service sentinel is "argument absent".
    # ``audio_ref`` uses the same omit-vs-explicit-None semantics so the
    # voice-recorder UX can attach the audio in a separate request after
    # the row exists. We split the call rather than ``**extra`` so mypy
    # can verify each kwarg's type against its sentinel union.
    kwargs: dict[str, Any] = {}
    if "task_id" in body.model_fields_set:
        kwargs["task_id"] = body.task_id
    if "audio_ref" in body.model_fields_set:
        kwargs["audio_ref"] = body.audio_ref
    channel = "web" if edit_session_id else "api"
    # ``update_note`` REPLACES title/body with what the request carries
    # (an omitted title is re-derived from the body, i.e. blanked when
    # there is none), so a structural-only PATCH must not reach it: it
    # would wipe the title of a note the caller only wanted to move. The
    # pair lives in note_tags, not on the row, so nothing there bumps
    # ``version`` -- exactly like /notes/{id}/tags, which carries no
    # version at all.
    content = {"title", "text", "task_id", "audio_ref"} & body.model_fields_set
    if content:
        v = await svc.update_note(
            ctx.session,
            org_id=ctx.org_id,
            actor_id=ctx.user_id,
            note_id=note_id,
            expected_version=body.expected_version,
            title=body.title,
            text=body.text,
            channel=channel,
            edit_session_id=edit_session_id,
            **kwargs,
        )
    else:
        v = (await svc.get_note(ctx.session, org_id=ctx.org_id, note_id=note_id)).version
    # PROJECT FIRST: a move that changes both ends is stated as
    # {project, client} and the project drags its client along, so
    # applying the client first would read as a contradiction against
    # the project the note still carries and 400.
    if "project_tag_id" in body.model_fields_set:
        if body.project_tag_id is None:
            # The un-share path (docs/adr/0021): drop the project, keep
            # the client, send the blobs back to the personal perimeter.
            # Legal for a note, never for a task. The service needs the
            # tag id to dispatch on; no project attached = nothing to do.
            current = await svc.project_tag_for_note(ctx.session, note_id=note_id)
            if current is not None:
                await svc.detach_tag(
                    ctx.session,
                    org_id=ctx.org_id,
                    actor_id=ctx.user_id,
                    note_id=note_id,
                    tag_id=current,
                )
        else:
            await require_tag_kind(
                ctx.session, org_id=ctx.org_id, tag_id=body.project_tag_id, kind=TagKind.project
            )
            await svc.attach_tag(
                ctx.session,
                org_id=ctx.org_id,
                actor_id=ctx.user_id,
                note_id=note_id,
                tag_id=body.project_tag_id,
            )
    if "client_tag_id" in body.model_fields_set:
        if body.client_tag_id is None:
            # A note has exactly one client: there is no legal state to
            # clear into, it is re-pointed by naming another one.
            raise DomainError(MessageCode.TAG_STRUCTURAL_REQUIRED)
        await require_tag_kind(
            ctx.session, org_id=ctx.org_id, tag_id=body.client_tag_id, kind=TagKind.client
        )
        await svc.attach_tag(
            ctx.session,
            org_id=ctx.org_id,
            actor_id=ctx.user_id,
            note_id=note_id,
            tag_id=body.client_tag_id,
        )
    return VersionOut(id=note_id, version=v)


# --- Note parts CRUD + reorder + ui-state (task 71c9d670 Phase 2a) ---


@router.get(
    "/{note_id}/parts",
    response_model=list[NotePartOut],
    tags=["garden"],
)
async def list_note_parts(
    note_id: uuid.UUID,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> list[NotePartOut]:
    """List the ordered parts of a note, with the caller's per-part
    collapse state. Useful when the SPA refetches just the parts
    after a reorder without reloading the whole note."""
    rows = await parts_svc.list_parts(ctx.session, org_id=ctx.org_id, note_id=note_id)
    ui = await parts_svc.get_ui_states_for_user(ctx.session, user_id=ctx.user_id, note_id=note_id)
    return [_part_out(p, ui_collapsed=ui.get(p.id, False)) for p in rows]


@router.post(
    "/{note_id}/parts",
    response_model=NotePartOut,
    tags=["garden"],
)
async def create_note_part(
    note_id: uuid.UUID,
    body: NotePartCreateIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> NotePartOut:
    """Append (default) or insert a part. Pass ``ord`` to insert at
    a specific position; every part at or after that ord is shifted
    forward by one in the same transaction."""
    part = await parts_svc.create_part(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        body=body.body,
        title=body.title,
        lang=body.lang,
        ord=body.ord,
    )
    return _part_out(part)


@router.post(
    "/{note_id}/parts/stream",
    response_model=NotePartOut,
    status_code=status.HTTP_201_CREATED,
    tags=["garden"],
)
async def create_note_part_stream(
    note_id: uuid.UUID,
    request: Request,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
    title: Annotated[str | None, Query(max_length=300)] = None,
    lang: Annotated[str | None, Query(max_length=16)] = None,
    ord: Annotated[int | None, Query(ge=0)] = None,
) -> NotePartOut:
    """Token-free create of a note part: the markdown body is the raw
    request body, streamed straight into the part's TEXT column instead
    of riding a tool argument (the inline-body analogue of
    ``POST /attachments/stream``; no S3 needed). Metadata (``title`` /
    ``lang`` / ``ord``) are query params. The body is size-capped
    (``note_body_max_bytes``) and must be valid UTF-8. Use the MCP
    ``add_note_part_instructions`` tool for the matching ``curl``."""
    body_text = await read_capped_text(request, max_bytes=get_settings().note_body_max_bytes)
    part = await parts_svc.create_part(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        body=body_text,
        title=title,
        lang=lang,
        ord=ord,
    )
    return _part_out(part)


@router.post(
    "/{note_id}/parts/{part_id}/append",
    response_model=AppendOut,
    tags=["garden"],
)
async def append_note_part(
    note_id: uuid.UUID,
    part_id: uuid.UUID,
    body: NotePartAppendIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
    edit_session_id: Annotated[str | None, Header(alias="X-Edit-Session-Id")] = None,
) -> AppendOut:
    """Append one chunk to a part's body without resending it -- stream a
    large markdown file in N ordered chunks (task 27f4d6c9). Each call
    asserts ``expected_version`` (the cursor returned by the previous
    chunk); chunks concatenate raw for byte-exact reassembly. Idempotent
    on replay; a different-version writer racing the same part gets
    ``stale_version``. Create the target part first with POST
    ``/{note_id}/parts`` (its body becomes chunk 0), then append the
    rest here. ``X-Edit-Session-Id`` (or ``operation_id`` in the body)
    coalesces the per-upload recovery revision."""
    channel = "web" if edit_session_id else "api"
    v, appended = await parts_svc.append_to_part(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        part_id=part_id,
        chunk=body.chunk,
        expected_version=body.expected_version,
        is_last=body.is_last,
        operation_id=body.operation_id or edit_session_id,
        channel=channel,
    )
    return AppendOut(id=part_id, version=v, appended_chars=appended)


@router.post(
    "/{note_id}/parts/{part_id}/prepend",
    response_model=AppendOut,
    tags=["garden"],
)
async def prepend_note_part(
    note_id: uuid.UUID,
    part_id: uuid.UUID,
    body: NotePartPrependIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
    edit_session_id: Annotated[str | None, Header(alias="X-Edit-Session-Id")] = None,
) -> AppendOut:
    """Prepend ``text`` to the front of a part's body without resending
    it (task 5662a07f). Single-shot, concurrency-safe via
    ``expected_version``. ``appended_chars`` in the response is the count
    of prepended characters."""
    channel = "web" if edit_session_id else "api"
    v, prepended = await parts_svc.prepend_to_part(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        part_id=part_id,
        text=body.text,
        expected_version=body.expected_version,
        operation_id=body.operation_id or edit_session_id,
        channel=channel,
    )
    return AppendOut(id=part_id, version=v, appended_chars=prepended)


@router.post(
    "/{note_id}/parts/{part_id}/replace",
    response_model=ReplaceOut,
    tags=["garden"],
)
async def replace_in_note_part(
    note_id: uuid.UUID,
    part_id: uuid.UUID,
    body: NotePartReplaceIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
    edit_session_id: Annotated[str | None, Header(alias="X-Edit-Session-Id")] = None,
) -> ReplaceOut:
    """Anchored find/replace inside ONE part without resending the body
    (task 5662a07f): swap the literal ``find`` for ``replace``.
    ``count=0`` replaces every occurrence; a positive ``count`` only the
    first N. Concurrency-safe via ``expected_version``. A no-op (``find``
    absent) returns ``replacements=0`` and leaves the version untouched."""
    channel = "web" if edit_session_id else "api"
    v, replacements = await parts_svc.replace_in_part(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        part_id=part_id,
        find=body.find,
        replace=body.replace,
        expected_version=body.expected_version,
        count=body.count,
        operation_id=body.operation_id or edit_session_id,
        channel=channel,
    )
    return ReplaceOut(id=part_id, version=v, replacements=replacements)


@router.patch(
    "/{note_id}/parts/{part_id}",
    response_model=VersionOut,
    tags=["garden"],
)
async def patch_note_part(
    note_id: uuid.UUID,
    part_id: uuid.UUID,
    body: NotePartPatchIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
    edit_session_id: Annotated[str | None, Header(alias="X-Edit-Session-Id")] = None,
) -> VersionOut:
    """Edit a part's body and/or lang. Pass ``lang=null`` explicitly
    to clear; omit the key to leave it untouched.

    ``X-Edit-Session-Id``: when supplied the note-level recovery
    revision coalesces with other edits in the same session window
    (same UX as PATCH /notes/{id}). Without the header the channel
    falls back to ``api`` and each save seals its own revision."""
    # Distinguish 'omit' from 'explicit null'. We need the FastAPI
    # body's model_fields_set, not just the value. Same pattern for
    # both omittable fields (``title``, ``lang``).
    kwargs: dict[str, Any] = {}
    if "title" in body.model_fields_set:
        kwargs["title"] = body.title
    if "lang" in body.model_fields_set:
        kwargs["lang"] = body.lang
    channel = "web" if edit_session_id else "api"
    v = await parts_svc.update_part(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        part_id=part_id,
        expected_version=body.expected_version,
        body=body.body,
        channel=channel,
        edit_session_id=edit_session_id,
        **kwargs,
    )
    return VersionOut(id=part_id, version=v)


@router.put(
    "/{note_id}/parts/{part_id}/body/stream",
    response_model=VersionOut,
    tags=["garden"],
)
async def replace_note_part_body_stream(
    note_id: uuid.UUID,
    part_id: uuid.UUID,
    request: Request,
    ctx: Annotated[TenantCtx, Depends(part_body_write_ctx, scope="function")],
    expected_version: Annotated[int, Query(ge=1)],
    edit_session_id: Annotated[str | None, Header(alias="X-Edit-Session-Id")] = None,
) -> VersionOut:
    """Token-free full-body replace of a note part: the new markdown is
    the raw request body, streamed into the part's TEXT column without
    resending it as a tool argument. ``expected_version`` is the
    optimistic cursor (a mismatch is ``stale_version`` -> 409); the body
    is size-capped (``note_body_max_bytes``) and must be valid UTF-8. An
    empty body clears the part. For incremental growth use ``/append``;
    this is the "I have the whole new body in a file" path. Use the MCP
    ``set_note_part_body_instructions`` tool for the matching ``curl``.

    Auth accepts a normal bearer (JWT / agent token, with X-Workspace-Id)
    or a scoped one-time capability token (``mycelium_cap_``) for this exact
    part, minted by the MCP ``set_note_part_body_capability`` tool and
    consumed here on success."""
    body_text = await read_capped_text(request, max_bytes=get_settings().note_body_max_bytes)
    channel = "web" if edit_session_id else "api"
    v = await parts_svc.update_part(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        part_id=part_id,
        expected_version=expected_version,
        body=body_text,
        channel=channel,
        edit_session_id=edit_session_id,
    )
    if ctx.capability_token_id is not None:
        # One-time: burn the capability now that the guarded write
        # committed (same transaction; a rolled-back write un-burns it).
        await capability_tokens_svc.consume(ctx.session, token_id=ctx.capability_token_id)
    return VersionOut(id=part_id, version=v)


@router.get("/{note_id}/parts/{part_id}/body/raw", tags=["garden"])
async def download_note_part_body_raw(
    note_id: uuid.UUID,
    part_id: uuid.UUID,
    ctx: Annotated[TenantCtx, Depends(part_body_read_ctx, scope="function")],
) -> Response:
    """Token-free raw download of a note part's markdown body. Returns the
    body as ``text/markdown`` with ``X-Version`` + ``X-Body-SHA256`` headers
    (the base gate the patch route checks). Bearer or a multi-use
    ``note_part_body:read`` capability for this part; the bytes never ride a
    tool argument. Use the MCP ``get_note_part_body_capability`` tool for the
    matching ``curl -D-``."""
    part = await parts_svc.get_part(ctx.session, org_id=ctx.org_id, part_id=part_id)
    body = part.body or ""
    return Response(
        content=body,
        media_type="text/markdown; charset=utf-8",
        headers=text_block_headers(version=part.version, body=body),
    )


@router.post(
    "/{note_id}/parts/{part_id}/body/patch",
    response_model=VersionOut,
    tags=["garden"],
)
async def patch_note_part_body(
    note_id: uuid.UUID,
    part_id: uuid.UUID,
    request: Request,
    ctx: Annotated[TenantCtx, Depends(part_body_patch_ctx, scope="function")],
    expected_version: Annotated[int, Query(ge=1)],
    base_sha256: Annotated[str, Query(min_length=64, max_length=64)],
    edit_session_id: Annotated[str | None, Header(alias="X-Edit-Session-Id")] = None,
) -> VersionOut:
    """Apply a strict unified diff (the raw request body) to a note part's
    markdown body. The base gate (``expected_version`` + ``base_sha256``,
    taken from the ``body/raw`` headers) refuses to apply if the live body
    drifted (409 ``patch.stale``); a diff that does not apply cleanly is 422
    (``patch.does_not_apply`` / ``patch.malformed``); nothing mutates on
    failure. Bearer or a single-use ``note_part_body:patch`` capability,
    consumed on success. Use the MCP ``patch_note_part_body_capability`` tool
    for the matching ``curl``."""
    patch = await read_patch_payload(request)
    channel = "web" if edit_session_id else "api"
    v = await parts_svc.apply_patch_to_part(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        part_id=part_id,
        expected_version=expected_version,
        patch=patch,
        base_sha256=base_sha256,
        channel=channel,
        edit_session_id=edit_session_id,
    )
    if ctx.capability_token_id is not None:
        await capability_tokens_svc.consume(ctx.session, token_id=ctx.capability_token_id)
    return VersionOut(id=part_id, version=v)


@router.post(
    "/{note_id}/parts/{part_id}/trash",
    status_code=204,
    tags=["garden"],
)
async def trash_note_part(
    note_id: uuid.UUID,
    part_id: uuid.UUID,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
    expected_version: Annotated[int | None, Query(ge=1)] = None,
) -> None:
    """Remove a part RESTORABLY: it moves to the trash keeping its id
    and content, and ``.../restore`` puts it back where it was. This is
    the ordinary delete for a part; the DELETE verb on the same path is
    the irreversible purge. Remaining parts keep their ords (no
    compaction) so deep links by ord survive.

    ``expected_version`` is an optional concurrency guard: supply it to
    refuse trashing a part that changed since you read it."""
    await parts_svc.trash_part(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        part_id=part_id,
        expected_version=expected_version,
    )


@router.post(
    "/{note_id}/parts/{part_id}/restore",
    response_model=NotePartOut,
    tags=["garden"],
)
async def restore_note_part(
    note_id: uuid.UUID,
    part_id: uuid.UUID,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> NotePartOut:
    """Put a trashed part back into its note with its original id, body
    and version. It aims for the ord it held; if that slot was taken in
    the meantime the parts at or after it shift forward by one. 404
    ``note.part.not_trashed`` when nothing matches (never trashed,
    already restored, or purged)."""
    part = await parts_svc.restore_part(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        part_id=part_id,
    )
    return _part_out(part)


@router.get(
    "/{note_id}/parts:trashed",
    response_model=list[NotePartTrashOut],
    tags=["garden"],
)
async def list_trashed_note_parts(
    note_id: uuid.UUID,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> list[NotePartTrashOut]:
    """Trashed parts of this note, most recently trashed first. The
    discovery half of the trash/restore pair: whoever wants a part back
    is rarely whoever removed it."""
    rows = await parts_svc.list_trashed(ctx.session, org_id=ctx.org_id, note_id=note_id)
    return [
        NotePartTrashOut(
            id=r.id,
            note_id=r.note_id,
            ord=r.ord,
            title=r.title,
            body=r.body,
            lang=r.lang,
            trashed_at=r.trashed_at,
            trashed_by=r.trashed_by,
        )
        for r in rows
    ]


@router.delete(
    "/{note_id}/parts/{part_id}",
    status_code=204,
    tags=["garden"],
)
async def delete_note_part(
    note_id: uuid.UUID,
    part_id: uuid.UUID,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> None:
    """PURGE a part: irreversible, nothing to restore from. Accepts a
    part in either state -- a live one is destroyed outright, an
    already-trashed one has its trash entry destroyed. For the
    restorable delete use ``POST .../trash``. Remaining parts keep
    their ords (no compaction) so deep links by ord survive."""
    await parts_svc.delete_part(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        part_id=part_id,
    )


@router.put(
    "/{note_id}/parts/order",
    response_model=list[NotePartOut],
    tags=["garden"],
)
async def reorder_note_parts(
    note_id: uuid.UUID,
    body: NotePartReorderIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> list[NotePartOut]:
    """Rewrite the entire ordering. ``part_ids`` must be the full set
    of the note's parts in the desired order; missing or extra ids
    raise a domain error so a reorder can never silently drop a row."""
    rows = await parts_svc.reorder_parts(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        part_ids=body.part_ids,
    )
    return [_part_out(p) for p in rows]


@router.put(
    "/{note_id}/parts/ui-state",
    response_model=list[NotePartOut],
    tags=["garden"],
)
async def set_all_note_parts_ui_state(
    note_id: uuid.UUID,
    body: NotePartUIStateIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> list[NotePartOut]:
    """Collapse / expand EVERY part of the note for the caller in one
    round-trip (the parts editor's collapse-all / expand-all toggle).
    User-scoped, last-write-wins. Returns the full parts list with the
    new collapse state so the SPA refreshes from a single response —
    same shape as the per-part endpoint, just note-wide.

    Declared before ``/{part_id}/ui-state`` so the literal ``ui-state``
    segment is never captured as a ``part_id``."""
    ui = await parts_svc.set_ui_states_bulk(
        ctx.session,
        org_id=ctx.org_id,
        user_id=ctx.user_id,
        note_id=note_id,
        collapsed=body.collapsed,
    )
    rows = await parts_svc.list_parts(ctx.session, org_id=ctx.org_id, note_id=note_id)
    return [_part_out(p, ui_collapsed=ui.get(p.id, body.collapsed)) for p in rows]


@router.put(
    "/{note_id}/parts/{part_id}/ui-state",
    response_model=NotePartOut,
    tags=["garden"],
)
async def set_note_part_ui_state(
    note_id: uuid.UUID,
    part_id: uuid.UUID,
    body: NotePartUIStateIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> NotePartOut:
    """Toggle the caller's collapse state for a part. User-scoped,
    last-write-wins. The response carries the full NotePartOut so
    the SPA can refresh its local state from a single round-trip."""
    await parts_svc.set_ui_state(
        ctx.session,
        org_id=ctx.org_id,
        user_id=ctx.user_id,
        part_id=part_id,
        collapsed=body.collapsed,
    )
    # Re-read so the response carries the canonical part + the new
    # collapse state in one shape (avoids the SPA needing a second
    # GET to refresh the row after toggle).
    rows = await parts_svc.list_parts(ctx.session, org_id=ctx.org_id, note_id=note_id)
    part = next((p for p in rows if p.id == part_id), None)
    if part is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND)
    return _part_out(part, ui_collapsed=body.collapsed)


@router.post(
    "/merge",
    response_model=NoteOut,
    tags=["garden"],
)
async def merge_notes(
    body: NoteMergeIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> NoteOut:
    """Fold the source note's parts into the target (task 71c9d670
    Phase 2b). Soft-deletes the source, stamps every moved part with
    ``merged_from_note_id``, and records a ``supersedes`` link
    (target → source) so the graph keeps the lineage. Returns the
    target as it now stands, parts included."""
    target = await parts_svc.merge_notes(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        source_note_id=body.source_note_id,
        target_note_id=body.target_note_id,
        strategy=body.strategy,
    )
    tagmap = await svc.tags_by_note(ctx.session, note_ids=[target.id])
    pid = await note_links_svc.primary_task_id_for_note(
        ctx.session, org_id=ctx.org_id, note_id=target.id
    )
    derived = await note_links_svc.derived_task_ids_for_notes(
        ctx.session, org_id=ctx.org_id, note_ids=[target.id]
    )
    counts = await note_links_svc.linked_task_counts_for_notes(
        ctx.session, org_id=ctx.org_id, note_ids=[target.id]
    )
    parts_rows = await parts_svc.list_parts(ctx.session, org_id=ctx.org_id, note_id=target.id)
    ui = await parts_svc.get_ui_states_for_user(ctx.session, user_id=ctx.user_id, note_id=target.id)
    return _out(
        target,
        tagmap.get(target.id, []),
        primary_task_id=pid,
        derived_task_ids=derived.get(target.id, []),
        linked_task_count=counts.get(target.id, 0),
        parts=[_part_out(p, ui_collapsed=ui.get(p.id, False)) for p in parts_rows],
    )


@router.post("/{note_id}/append", response_model=AppendOut)
async def append_note(
    note_id: uuid.UUID,
    body: NoteAppendIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> AppendOut:
    """Task 4ac39ecf: context-blind append for ``note.summary`` /
    ``note.transcript``. The caller never has to read the body first
    (saves context for MCP / LLM tools). When ``expected_version`` is
    omitted, the helper appends onto whatever state the row currently
    has -- safe for log-style writers."""
    new_version, appended = await svc.append_to_note_field(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        target=body.target,
        text=body.text,
        separator=body.separator,
        expected_version=body.expected_version,
        dedupe_if_tail_matches=body.dedupe_if_tail_matches,
    )
    return AppendOut(id=note_id, version=new_version, appended_chars=appended)


@router.post("/{note_id}/delete", response_model=VersionOut)
async def delete_note(
    note_id: uuid.UUID,
    body: ExpectedVersionIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> VersionOut:
    v = await svc.soft_delete_note(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        expected_version=body.expected_version,
    )
    return VersionOut(id=note_id, version=v)


@router.post("/{note_id}/restore", response_model=VersionOut)
async def restore_note(
    note_id: uuid.UUID,
    body: ExpectedVersionIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> VersionOut:
    v = await svc.restore_note(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        expected_version=body.expected_version,
    )
    return VersionOut(id=note_id, version=v)


@router.post("/{note_id}/archive", response_model=VersionOut)
async def archive_note(
    note_id: uuid.UUID,
    body: ExpectedVersionIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> VersionOut:
    v = await svc.archive_note(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        expected_version=body.expected_version,
        archived=True,
    )
    return VersionOut(id=note_id, version=v)


@router.post("/{note_id}/unarchive", response_model=VersionOut)
async def unarchive_note(
    note_id: uuid.UUID,
    body: ExpectedVersionIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> VersionOut:
    v = await svc.archive_note(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        expected_version=body.expected_version,
        archived=False,
    )
    return VersionOut(id=note_id, version=v)


@router.post("/{note_id}/protect", response_model=VersionOut)
async def protect_note(
    note_id: uuid.UUID,
    body: ExpectedVersionIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> VersionOut:
    """Fase P (task 561c6aca): mark the note as finished prose the distiller
    must never compact (excluded from every distillation candidate/surface).
    The user has the last word; reversible via ``unprotect``."""
    v = await svc.protect_note(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        expected_version=body.expected_version,
        protected=True,
    )
    return VersionOut(id=note_id, version=v)


@router.post("/{note_id}/unprotect", response_model=VersionOut)
async def unprotect_note(
    note_id: uuid.UUID,
    body: ExpectedVersionIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> VersionOut:
    v = await svc.protect_note(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        expected_version=body.expected_version,
        protected=False,
    )
    return VersionOut(id=note_id, version=v)


@router.post("/{note_id}/transcribe", response_model=NoteOut)
async def transcribe(
    note_id: uuid.UUID,
    body: NoteTranscribeIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> NoteOut:
    n = await svc.transcribe(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        operation_id=body.operation_id,
        embed=body.embed,
    )
    pid = await note_links_svc.primary_task_id_for_note(
        ctx.session, org_id=ctx.org_id, note_id=n.id
    )
    return _out(
        n,
        primary_task_id=pid,
        transcript=await svc.get_body(ctx.session, note_id=n.id),
    )


@router.post("/conversations", response_model=NoteOut)
async def start_conversation(
    body: ConversationStartIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> NoteOut:
    n = await svc.create_note(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        kind=NoteKind.conversation,
        project_id=body.project_id,
        title=body.title,
    )
    return _out(n, transcript="")


@router.post("/{note_id}/messages", response_model=NoteTurnOut)
async def append_message(
    note_id: uuid.UUID,
    body: AppendMessageIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> NoteTurnOut:
    reply = await svc.append_message(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        content=body.content,
        operation_id=body.operation_id,
    )
    return _turn(reply)


@router.get("/{note_id}/turns", response_model=list[NoteTurnOut])
async def list_turns(
    note_id: uuid.UUID,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> list[NoteTurnOut]:
    rows = await svc.list_turns(ctx.session, org_id=ctx.org_id, note_id=note_id)
    return [_turn(t) for t in rows]


@router.post("/synthesize", response_model=SynthOut)
async def synthesize(
    body: SynthesizeIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> SynthOut:
    res = await svc.synthesize(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        text=body.text,
        operation_id=body.operation_id,
    )
    return SynthOut(audio_ref=res["audio_ref"], model_id=res["model_id"])


@router.post("/command", response_model=NoteOut)
async def command(
    body: CommandIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> NoteOut:
    n = await svc.run_command(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        text=body.text,
    )
    pid = await note_links_svc.primary_task_id_for_note(
        ctx.session, org_id=ctx.org_id, note_id=n.id
    )
    return _out(
        n,
        primary_task_id=pid,
        transcript=await svc.get_body(ctx.session, note_id=n.id),
    )


@router.post("/{note_id}/erase", response_model=NoteEraseOut)
async def erase(
    note_id: uuid.UUID,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> NoteEraseOut:
    res = await svc.gdpr_erase_note(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
    )
    return NoteEraseOut(
        audio_ref=res.audio_ref,
        memory_blobs_deleted=res.memory_blobs_deleted,
    )


# ----------------------------------------------------------------------
# Quick-create endpoint (Apple Shortcut / Tasker / cURL one-liner).
# Auth: agent_token (``mycelium_at_...``). The user mints one in
# /settings/ai-assistants, pastes it into the Shortcut. The Shortcut
# resolves the project by case-insensitive partial name (or UUID).
# Designed to be hit from a single ``Get Contents of URL`` action on
# iOS Shortcuts; no JWT, no workspace header, just the bearer.


class QuickCreateIn(BaseModel):
    """Body for the Apple Shortcut / iOS Dictation flow. ``project``
    is a project name (case-insensitive partial match) or a UUID; if
    omitted, the note lands in the default project of the assistant's
    workspace. ``kind`` defaults to ``text`` because dictation is
    text-first; voice notes still go through the /notes flow."""

    project: str | None = Field(default=None, max_length=200)
    text: str = Field(min_length=1, max_length=20000)
    kind: NoteKind = NoteKind.text
    title: str | None = Field(default=None, max_length=300)


class QuickCreateOut(BaseModel):
    id: uuid.UUID
    project_id: uuid.UUID | None
    kind: NoteKind


async def _agent_principal(
    authorization: Annotated[str | None, Header()] = None,
) -> agent_tokens_svc.AuthenticatedAgent:
    """Resolve the ``Authorization: Bearer mycelium_at_...`` header to an
    ``AuthenticatedAgent``. 401 if missing / malformed / unknown.
    Mirrors the MCP HTTP transport bearer middleware (mcp/server_http)
    but at the FastAPI dep boundary so this endpoint can be reached
    from the regular ingress without going through /mcp."""
    if not authorization or not authorization.lower().startswith("bearer "):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Missing or malformed Authorization header",
        )
    raw = authorization.split(" ", 1)[1].strip()
    if not agent_tokens_svc.is_agent_token(raw):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Bearer is not a Mycelium agent token",
        )
    principal = await agent_tokens_svc.authenticate(raw)
    if principal is None:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Unknown / revoked / expired token",
        )
    return principal


async def _resolve_project(org_id: uuid.UUID, needle: str | None) -> uuid.UUID | None:
    """``needle`` may be a UUID (exact match), a project name (exact,
    case-insensitive), or a substring (case-insensitive partial). The
    first matching project tag wins; absent project yields ``None``
    (create_note falls back to the default ``General`` project)."""
    if not needle:
        return None
    try:
        return uuid.UUID(needle)
    except ValueError:
        pass
    async with admin_session() as session:
        # Set the org GUC so RLS lets us see the tags.
        from sqlalchemy import text as sql_text

        await session.execute(
            sql_text("SELECT set_config('app.current_org', :o, true)"),
            {"o": str(org_id)},
        )
        # Exact case-insensitive first; partial as fallback.
        exact = (
            await session.execute(
                select(Tag.id)
                .join(ProjectProfile, ProjectProfile.tag_id == Tag.id)
                .where(Tag.kind == TagKind.project)
                .where(Tag.name.ilike(needle))
                .limit(1)
            )
        ).scalar_one_or_none()
        if exact:
            return exact
        partial = (
            await session.execute(
                select(Tag.id)
                .join(ProjectProfile, ProjectProfile.tag_id == Tag.id)
                .where(Tag.kind == TagKind.project)
                .where(Tag.name.ilike(f"%{needle}%"))
                .limit(1)
            )
        ).scalar_one_or_none()
        return partial


@router.post("/quick-create", response_model=QuickCreateOut)
async def quick_create(
    body: QuickCreateIn,
    principal: Annotated[agent_tokens_svc.AuthenticatedAgent, Depends(_agent_principal)],
) -> QuickCreateOut:
    """Single-shot note creation for Apple Shortcuts, Tasker, or any
    one-liner client. The agent token's bound user becomes the actor.
    Resolves ``project`` to a project tag; creates the note via
    ``services/notes.create_note``."""
    project_id = await _resolve_project(principal.org_id, body.project)
    async with admin_session() as session:
        from sqlalchemy import text as sql_text

        await session.execute(
            sql_text("SELECT set_config('app.current_org', :o, true)"),
            {"o": str(principal.org_id)},
        )
        await session.execute(
            sql_text("SELECT set_config('app.current_user', :u, true)"),
            {"u": str(principal.user_id)},
        )
        note = await svc.create_note(
            session,
            org_id=principal.org_id,
            actor_id=principal.user_id,
            kind=body.kind,
            text=body.text,
            title=body.title,
            project_id=project_id,
        )
        await session.commit()
    # ``project_id`` is now stored in ``note_tags``; the resolved
    # value comes back as-is for the caller's reference.
    return QuickCreateOut(id=note.id, project_id=project_id, kind=note.kind)


# ---------------------------------------------------------------------------
# Garden ecosystem (docs/adr/0029 P1) endpoints. Set maturity, promote,
# derive a fruit task, link notes to notes/tasks. Tags every endpoint
# with "garden" so the OpenAPI surface stays grouped.
# ---------------------------------------------------------------------------


@router.post(
    "/{note_id}/maturity",
    response_model=NoteOut,
    tags=["garden"],
)
async def set_note_maturity(
    note_id: uuid.UUID,
    body: NoteSetMaturityIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> NoteOut:
    n = await note_links_svc.set_maturity(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        maturity=body.maturity,
    )
    tagmap = await svc.tags_by_note(ctx.session, note_ids=[n.id])
    pid = await note_links_svc.primary_task_id_for_note(
        ctx.session, org_id=ctx.org_id, note_id=n.id
    )
    return _out(
        n,
        tagmap.get(n.id, []),
        primary_task_id=pid,
        transcript=await svc.get_body(ctx.session, note_id=n.id),
    )


@router.post(
    "/{note_id}/promote",
    response_model=DerivedTaskOut,
    tags=["garden"],
)
async def promote_note(
    note_id: uuid.UUID,
    body: NotePromoteIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> DerivedTaskOut:
    task, link = await note_links_svc.promote_note_to_task(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        title=body.title,
    )
    return DerivedTaskOut(task_id=task.id, link=_task_link_out(link))


@router.post(
    "/{note_id}/derive-task",
    response_model=DerivedTaskOut,
    tags=["garden"],
)
async def derive_task(
    note_id: uuid.UUID,
    body: NoteDeriveTaskIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> DerivedTaskOut:
    task, link = await note_links_svc.derive_task_from_note(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        title=body.title,
        description=body.description,
        estimate_effort_h=body.estimate_effort_h,
        extra_tag_ids=list(body.extra_tag_ids),
    )
    return DerivedTaskOut(task_id=task.id, link=_task_link_out(link))


@router.post(
    "/{note_id}/links",
    response_model=NoteLinkOut,
    tags=["garden"],
)
async def link_notes(
    note_id: uuid.UUID,
    body: NoteLinkIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> NoteLinkOut:
    # ``note_id`` from the URL is the parent (the link's "from"); the
    # body carries the child and the kind. We accept the parent in
    # both places defensively.
    if body.parent_note_id != note_id:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST)
    link = await note_links_svc.link_notes(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        parent_note_id=body.parent_note_id,
        child_note_id=body.child_note_id,
        kind=body.kind,
    )
    return _link_out(link)


@router.delete(
    "/{note_id}/links",
    status_code=204,
    tags=["garden"],
)
async def unlink_notes(
    note_id: uuid.UUID,
    child_note_id: uuid.UUID,
    kind: str,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> None:
    removed = await note_links_svc.unlink_notes(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        parent_note_id=note_id,
        child_note_id=child_note_id,
        kind=kind,
    )
    if not removed:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND)


@router.get(
    "/{note_id}/links",
    response_model=NoteWithLinksOut,
    tags=["garden"],
)
async def list_note_links(
    note_id: uuid.UUID,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> NoteWithLinksOut:
    n = await svc.get_note(ctx.session, org_id=ctx.org_id, note_id=note_id)
    tagmap = await svc.tags_by_note(ctx.session, note_ids=[n.id])
    outgoing, incoming = await note_links_svc.list_note_links(
        ctx.session, org_id=ctx.org_id, note_id=note_id
    )
    task_links = await note_links_svc.list_note_task_links(
        ctx.session, org_id=ctx.org_id, note_id=note_id
    )
    pid = await note_links_svc.primary_task_id_for_note(
        ctx.session, org_id=ctx.org_id, note_id=n.id
    )
    return NoteWithLinksOut(
        note=_out(
            n,
            tagmap.get(n.id, []),
            primary_task_id=pid,
            transcript=await svc.get_body(ctx.session, note_id=n.id),
        ),
        outgoing=[_link_out(o) for o in outgoing],
        incoming=[_link_out(o) for o in incoming],
        task_links=[_task_link_out(o) for o in task_links],
    )


@router.post(
    "/{note_id}/task-links",
    response_model=NoteTaskLinkOut,
    tags=["garden"],
)
async def add_note_task_link(
    note_id: uuid.UUID,
    body: NoteTaskLinkIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
    claims: Annotated[dict[str, Any], Depends(current_claims)],
) -> NoteTaskLinkOut:
    """Create a typed note↔task link from the note side. ``kind`` picks
    the named operation: ``subject`` → start_task_on_note,
    ``artifact`` → record_task_artifact. ``derived_from`` and
    ``promoted_from`` are intentionally NOT accepted here: those are
    creation-with-link operations, not free linkage (see
    /notes/{id}/derive-task and /promote).

    The two operations require different scopes (subject is a notes:write op,
    artifact a tasks:write one), which one route key cannot express, so the
    app-level gate only checks the any-of baseline and the exact key is enforced
    per ``kind`` here (task c19f2f63, review #5)."""
    if body.kind == "subject":
        require_agent_scope(claims, "notes:write")
        link = await note_links_svc.start_task_on_note(
            ctx.session,
            org_id=ctx.org_id,
            actor_id=ctx.user_id,
            task_id=body.task_id,
            note_id=note_id,
        )
    elif body.kind == "artifact":
        require_agent_scope(claims, "tasks:write")
        link = await note_links_svc.record_task_artifact(
            ctx.session,
            org_id=ctx.org_id,
            actor_id=ctx.user_id,
            task_id=body.task_id,
            note_id=note_id,
        )
    else:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST)
    return _task_link_out(link)


@router.delete(
    "/{note_id}/task-links",
    status_code=204,
    tags=["garden"],
)
async def remove_note_task_link(
    note_id: uuid.UUID,
    task_id: uuid.UUID,
    kind: str,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> None:
    """Idempotent removal: returns 404 only if no row matched. Refuses
    ``promoted_from`` (a transplant cannot be undone via unlink; the
    note has ``promoted_at`` set as a side-effect)."""
    removed = await note_links_svc.unlink_note_task(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        task_id=task_id,
        kind=kind,
    )
    if not removed:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND)


def _revision_out(rev: Any, seq: int | None = None) -> RevisionOut:
    """Serialize an EntityRevision ORM row. ``org_id`` is dropped: the
    revision lives in the caller's tenant already (RLS). ``seq`` is the
    revision's 1-based chronological position (the timeline's ``v{n}``),
    computed by the list endpoint; None on the single-revision GET."""
    return RevisionOut(
        id=rev.id,
        entity_kind=rev.entity_kind,
        entity_id=rev.entity_id,
        snapshot=rev.snapshot or {},
        changed_fields=list(rev.changed_fields or []),
        channel=rev.channel,
        actor_id=rev.actor_id,
        actor_kind=rev.actor_kind,
        actor_subject_id=rev.actor_subject_id,
        edit_session_id=rev.edit_session_id,
        version_from=rev.version_from,
        version_to=rev.version_to,
        seq=seq,
        edit_count=rev.edit_count,
        started_at=rev.started_at,
        last_edit_at=rev.last_edit_at,
        sealed_at=rev.sealed_at,
        restored_from=rev.restored_from,
        summary=rev.summary,
    )


@router.get("/{note_id}/revisions", response_model=list[RevisionOut])
async def list_note_revisions(
    note_id: uuid.UUID,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
    limit: Annotated[int, Query(ge=1, le=200)] = 50,
    before: Annotated[datetime.datetime | None, Query()] = None,
) -> list[RevisionOut]:
    """Timeline of revisions for this note, most recent first."""
    await svc.get_note(ctx.session, org_id=ctx.org_id, note_id=note_id, include_deleted=True)
    rows = await rev_svc.list_revisions(
        ctx.session,
        entity_kind=rev_svc.ENTITY_KIND_NOTE,
        entity_id=note_id,
        limit=limit,
        before=before,
    )
    seqs = await rev_svc.revision_sequence(
        ctx.session,
        entity_kind=rev_svc.ENTITY_KIND_NOTE,
        entity_id=note_id,
        only_ids=[r.id for r in rows],
    )
    return [_revision_out(r, seq=seqs.get(r.id)) for r in rows]


@router.get("/{note_id}/revisions/{rev_id}", response_model=RevisionOut)
async def get_note_revision(
    note_id: uuid.UUID,
    rev_id: uuid.UUID,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> RevisionOut:
    rev = await rev_svc.get_revision(
        ctx.session,
        revision_id=rev_id,
        entity_kind=rev_svc.ENTITY_KIND_NOTE,
        entity_id=note_id,
    )
    return _revision_out(rev)


@router.patch("/{note_id}/revisions/{rev_id}", response_model=RevisionOut)
async def update_note_revision_summary(
    note_id: uuid.UUID,
    rev_id: uuid.UUID,
    body: RevisionSummaryIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> RevisionOut:
    """Set / clear the ``summary`` label on a revision. Mirror of the
    /tasks endpoint; see that one for the contract."""
    rev = await rev_svc.set_summary(
        ctx.session,
        revision_id=rev_id,
        summary=body.summary,
        entity_kind=rev_svc.ENTITY_KIND_NOTE,
        entity_id=note_id,
    )
    return _revision_out(rev)


@router.post("/{note_id}/revisions/{rev_id}/restore", response_model=VersionOut)
async def restore_note_revision(
    note_id: uuid.UUID,
    rev_id: uuid.UUID,
    body: RevisionRestoreIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> VersionOut:
    """Apply the snapshot's restorable fields (``title`` /
    ``transcript``) back to the note. Logged as a NEW sealed
    revision on the ``restore`` channel with ``restored_from``."""
    version = await svc.restore_revision(
        ctx.session,
        org_id=ctx.org_id,
        actor_id=ctx.user_id,
        note_id=note_id,
        revision_id=rev_id,
        expected_version=body.expected_version,
        fields=body.fields,
    )
    return VersionOut(id=note_id, version=version)


@router.post("/{note_id}/edit-session/seal", response_model=EditSessionSealOut)
async def seal_note_edit_session(
    note_id: uuid.UUID,
    body: EditSessionSealIn,
    ctx: Annotated[TenantCtx, Depends(tenant_ctx, scope="function")],
) -> EditSessionSealOut:
    count = await rev_svc.seal_open(
        ctx.session,
        entity_kind=rev_svc.ENTITY_KIND_NOTE,
        entity_id=note_id,
        actor_id=ctx.user_id,
        edit_session_id=body.edit_session_id,
    )
    return EditSessionSealOut(sealed=count)
