"""Official MessaggiTypes_v1.1 XSD validation for all SdI notifications --
the schema gate that runs before any cycle-specific routing.

The schema-on-disk requires ``ds:Signature``; the validator relaxes that in
memory (signature verification is a separate concern). Tests cover the
*business* shape of every notification type known to the schema, the
namespace guard, and the unknown-root guard.
"""

from __future__ import annotations

import pytest

from flow_core.services.sdi_notification_xsd import (
    ACTIVE_CYCLE_ROOTS,
    ALL_NOTIFICATION_ROOTS,
    DUAL_CYCLE_ROOTS,
    NS_MESSAGGI,
    NS_MESSAGGI_PRIVATI,
    RECEIVER_CYCLE_ROOTS,
    validate_sdi_notification,
)


def _rc(ident: str = "123456789012") -> str:
    return (
        f'<m:RicevutaConsegna xmlns:m="{NS_MESSAGGI}" versione="1.0">'
        f"<IdentificativoSdI>{ident}</IdentificativoSdI>"
        f"<NomeFile>IT01234567890_00001.xml</NomeFile>"
        f"<DataOraRicezione>2026-05-25T10:00:00</DataOraRicezione>"
        f"<DataOraConsegna>2026-05-25T10:01:00</DataOraConsegna>"
        f"<Destinatario><Codice>ABCDEFG</Codice><Descrizione>A</Descrizione></Destinatario>"
        f"<MessageId>MID00001</MessageId>"
        f"</m:RicevutaConsegna>"
    )


def _ns(ident: str = "111") -> str:
    return (
        f'<m:NotificaScarto xmlns:m="{NS_MESSAGGI}" versione="1.0">'
        f"<IdentificativoSdI>{ident}</IdentificativoSdI>"
        f"<NomeFile>x.xml</NomeFile>"
        f"<DataOraRicezione>2026-05-25T10:00:00</DataOraRicezione>"
        f"<ListaErrori><Errore><Codice>00001</Codice>"
        f"<Descrizione>boom</Descrizione></Errore></ListaErrori>"
        f"<MessageId>M</MessageId>"
        f"</m:NotificaScarto>"
    )


def _mc(ident: str = "222") -> str:
    return (
        f'<m:NotificaMancataConsegna xmlns:m="{NS_MESSAGGI}" versione="1.0">'
        f"<IdentificativoSdI>{ident}</IdentificativoSdI>"
        f"<NomeFile>x.xml</NomeFile>"
        f"<DataOraRicezione>2026-05-25T10:00:00</DataOraRicezione>"
        f"<MessageId>M</MessageId>"
        f"</m:NotificaMancataConsegna>"
    )


def _at(ident: str = "333") -> str:
    return (
        f'<m:AttestazioneTrasmissioneFattura xmlns:m="{NS_MESSAGGI}" versione="1.0">'
        f"<IdentificativoSdI>{ident}</IdentificativoSdI>"
        f"<NomeFile>x.xml</NomeFile>"
        f"<DataOraRicezione>2026-05-25T10:00:00</DataOraRicezione>"
        f"<Destinatario><Codice>ABCDEFG</Codice><Descrizione>A</Descrizione></Destinatario>"
        f"<MessageId>M</MessageId>"
        f"<HashFileOriginale>abc</HashFileOriginale>"
        f"</m:AttestazioneTrasmissioneFattura>"
    )


def _ne(ident: str = "444") -> str:
    # NotificaEsito wraps the original EsitoCommittente generated by the buyer
    # and relayed back to the transmitter.
    return (
        f'<m:NotificaEsito xmlns:m="{NS_MESSAGGI}" versione="1.0">'
        f"<IdentificativoSdI>{ident}</IdentificativoSdI>"
        f"<NomeFile>x.xml</NomeFile>"
        f'<EsitoCommittente versione="1.0">'
        f"<IdentificativoSdI>{ident}</IdentificativoSdI>"
        f"<Esito>EC01</Esito>"
        f"</EsitoCommittente>"
        f"<MessageId>M</MessageId>"
        f"</m:NotificaEsito>"
    )


def _dt(ident: str = "555") -> str:
    return (
        f'<m:NotificaDecorrenzaTermini xmlns:m="{NS_MESSAGGI}" versione="1.0">'
        f"<IdentificativoSdI>{ident}</IdentificativoSdI>"
        f"<NomeFile>x.xml</NomeFile>"
        f"<MessageId>M</MessageId>"
        f"</m:NotificaDecorrenzaTermini>"
    )


def _ec(ident: str = "666") -> str:
    # Committente's outcome notice (we build this when acting as buyer); SdI
    # also relays it inside NotificaEsito, but as a standalone root it's the
    # receiver-cycle message.
    return (
        f'<m:NotificaEsitoCommittente xmlns:m="{NS_MESSAGGI}" versione="1.0">'
        f"<IdentificativoSdI>{ident}</IdentificativoSdI>"
        f"<Esito>EC01</Esito>"
        f"</m:NotificaEsitoCommittente>"
    )


def _se(ident: str = "777") -> str:
    return (
        f'<m:ScartoEsitoCommittente xmlns:m="{NS_MESSAGGI}" versione="1.0">'
        f"<IdentificativoSdI>{ident}</IdentificativoSdI>"
        f"<Scarto>EN00</Scarto>"
        f"<MessageId>M</MessageId>"
        f"</m:ScartoEsitoCommittente>"
    )


def _mt(ident: str = "888") -> str:
    return (
        f'<m:MetadatiInvioFile xmlns:m="{NS_MESSAGGI}" versione="1.0">'
        f"<IdentificativoSdI>{ident}</IdentificativoSdI>"
        f"<NomeFile>x.xml</NomeFile>"
        f"<CodiceDestinatario>ABCDEFG</CodiceDestinatario>"
        f"<Formato>FPR12</Formato>"
        f"<TentativiInvio>1</TentativiInvio>"
        f"<MessageId>M</MessageId>"
        f"</m:MetadatiInvioFile>"
    )


def _rs(ident: str = "999") -> str:
    # B2B/B2C scarto in the privati namespace; validated structurally (we do
    # not vendor that schema), so a well-formed instance passes.
    return (
        f'<m:RicevutaScarto xmlns:m="{NS_MESSAGGI_PRIVATI}" versione="1.0">'
        f"<IdentificativoSdI>{ident}</IdentificativoSdI>"
        f"<NomeFile>x.xml</NomeFile>"
        f"<DataOraRicezione>2026-05-30T10:00:00</DataOraRicezione>"
        f"<ListaErrori><Errore><Codice>00300</Codice>"
        f"<Descrizione>boom</Descrizione></Errore></ListaErrori>"
        f"</m:RicevutaScarto>"
    )


def _rir(ident: str = "1010") -> str:
    return (
        f'<m:RicevutaImpossibilitaRecapito xmlns:m="{NS_MESSAGGI_PRIVATI}" versione="1.0">'
        f"<IdentificativoSdI>{ident}</IdentificativoSdI>"
        f"<NomeFile>x.xml</NomeFile>"
        f"<DataOraRicezione>2026-05-30T10:00:00</DataOraRicezione>"
        f"</m:RicevutaImpossibilitaRecapito>"
    )


_BUILDERS = {
    "RicevutaConsegna": _rc,
    "NotificaScarto": _ns,
    "NotificaMancataConsegna": _mc,
    "AttestazioneTrasmissioneFattura": _at,
    "NotificaEsito": _ne,
    "NotificaDecorrenzaTermini": _dt,
    "NotificaEsitoCommittente": _ec,
    "ScartoEsitoCommittente": _se,
    "MetadatiInvioFile": _mt,
    "RicevutaScarto": _rs,
    "RicevutaImpossibilitaRecapito": _rir,
}


@pytest.mark.parametrize("root", sorted(ALL_NOTIFICATION_ROOTS))
def test_every_known_notification_validates(root: str) -> None:
    assert validate_sdi_notification(_BUILDERS[root]()) == []


def test_subsets_partition_the_universe() -> None:
    # Active + Receiver + Dual must cover every known root with no overlap
    # except where DT is intentionally shared by both cycle handlers.
    assert ACTIVE_CYCLE_ROOTS | RECEIVER_CYCLE_ROOTS | DUAL_CYCLE_ROOTS == ALL_NOTIFICATION_ROOTS
    assert ACTIVE_CYCLE_ROOTS & RECEIVER_CYCLE_ROOTS == set()
    assert DUAL_CYCLE_ROOTS == {"NotificaDecorrenzaTermini"}


def test_known_root_membership_is_explicit() -> None:
    # Guard against schema drift: if AdE adds a new root to MessaggiTypes,
    # this test pins us to acknowledge it before silently accepting.
    assert ALL_NOTIFICATION_ROOTS == {
        "RicevutaConsegna",
        "NotificaScarto",
        "NotificaMancataConsegna",
        "AttestazioneTrasmissioneFattura",
        "NotificaEsito",
        "NotificaDecorrenzaTermini",
        "NotificaEsitoCommittente",
        "ScartoEsitoCommittente",
        "MetadatiInvioFile",
        # B2B/B2C privati roots (ivaservizi namespace, structural-only check):
        "RicevutaScarto",
        "RicevutaImpossibilitaRecapito",
    }


def test_wrong_namespace_is_rejected() -> None:
    bad = (
        '<m:RicevutaConsegna xmlns:m="urn:x">'
        "<IdentificativoSdI>1</IdentificativoSdI></m:RicevutaConsegna>"
    )
    errors = validate_sdi_notification(bad)
    assert errors and "is neither the PA messaggi namespace" in errors[0]


def test_missing_namespace_is_rejected() -> None:
    bare = "<RicevutaConsegna><IdentificativoSdI>1</IdentificativoSdI></RicevutaConsegna>"
    errors = validate_sdi_notification(bare)
    assert errors and "is neither the PA messaggi namespace" in errors[0]


def test_unknown_root_is_rejected_with_namespace() -> None:
    foo = f'<m:Foo xmlns:m="{NS_MESSAGGI}"/>'
    errors = validate_sdi_notification(foo)
    assert errors and "not a known SdI notification" in errors[0]


def test_missing_required_field_is_rejected() -> None:
    # RC without DataOraConsegna must fail XSD validation.
    incomplete = (
        f'<m:RicevutaConsegna xmlns:m="{NS_MESSAGGI}" versione="1.0">'
        f"<IdentificativoSdI>1</IdentificativoSdI>"
        f"<NomeFile>x.xml</NomeFile>"
        f"<DataOraRicezione>2026-05-25T10:00:00</DataOraRicezione>"
        f"<Destinatario><Codice>ABCDEFG</Codice><Descrizione>A</Descrizione></Destinatario>"
        f"<MessageId>M</MessageId>"
        f"</m:RicevutaConsegna>"
    )
    errors = validate_sdi_notification(incomplete)
    assert errors and any("DataOraConsegna" in e for e in errors)


def test_malformed_xml_is_rejected_cleanly() -> None:
    errors = validate_sdi_notification(b"not xml")
    assert errors == [e for e in errors if "not well-formed" in e.lower()]
    assert errors


def test_real_payload_with_signature_passes() -> None:
    # The wire payload from SdI is XAdES-signed: a Signature placeholder must
    # not break validation (it is allowed by the relaxed schema, not stripped).
    with_sig = (
        f'<m:RicevutaConsegna xmlns:m="{NS_MESSAGGI}" '
        f'xmlns:ds="http://www.w3.org/2000/09/xmldsig#" versione="1.0">'
        f"<IdentificativoSdI>1</IdentificativoSdI>"
        f"<NomeFile>x.xml</NomeFile>"
        f"<DataOraRicezione>2026-05-25T10:00:00</DataOraRicezione>"
        f"<DataOraConsegna>2026-05-25T10:01:00</DataOraConsegna>"
        f"<Destinatario><Codice>ABCDEFG</Codice><Descrizione>A</Descrizione></Destinatario>"
        f"<MessageId>M</MessageId>"
        f"<ds:Signature>"
        f"<ds:SignedInfo>"
        f'<ds:CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>'
        f'<ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>'
        f'<ds:Reference URI=""><ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>'
        f"<ds:DigestValue>YWJjZGVmZ2g=</ds:DigestValue></ds:Reference>"
        f"</ds:SignedInfo>"
        f"<ds:SignatureValue>YWJjZGVmZ2g=</ds:SignatureValue>"
        f"</ds:Signature>"
        f"</m:RicevutaConsegna>"
    )
    assert validate_sdi_notification(with_sig) == []
